### ISSUE TITLE
sigsegv on runc restore

### ISSUE THREAD

**Issue by kolyshkin** [checkpoint-restore/criu#1035]
This was found once while running CI for opencontainers/runc#2335. The complete error is here:
https://travis-ci.org/github/opencontainers/runc/jobs/678293808

This has happened while running the integration test on checkpointing (https://github.com/opencontainers/runc/blob/cdce577dcf751b5c18e228cf33f72ad5d095d281/tests/integration/checkpoint.bats#L194).

The bug happened here: https://github.com/opencontainers/runc/blob/cdce577dcf751b5c18e228cf33f72ad5d095d281/libcontainer/container_linux.go#L1572

The except with the segv is here:
```
not ok 12 checkpoint and restore in external network namespace

(from function `testcontainer' in file tests/integration/helpers.bash, line 317,
 in test file tests/integration/checkpoint.bats, line 251)
  `testcontainer test_busybox running' failed

runc list (status=0):
ID          PID         STATUS      BUNDLE      CREATED     OWNER
runc spec (status=0):

runc run -d --console-socket /tmp/console.sock test_busybox (status=0):

runc state test_busybox (status=0):
{
  "ociVersion": "1.0.2",
  "id": "test_busybox",
  "pid": 58656,
  "status": "running",
  "bundle": "/tmp/busyboxtest",
  "rootfs": "/tmp/busyboxtest/rootfs",
  "created": "2020-04-22T19:30:44.618940367Z",
  "owner": ""
}

runc --criu /usr/local/sbin/criu checkpoint --work-path ./work-dir test_busybox (status=0):

(00.031958) mnt: 	368: 27:/ @ ./dev/shm
(00.036887) mnt: 	367: 26:/ @ ./dev/pts
(00.036902) mnt: 	366: 25:/ @ ./dev
(00.036905) mnt: Mount is not fully visible ./dev
(00.036940) mnt: 	mount has children ./dev
(00.036962) Error (criu/mount.c:1117): mnt: Can't create a temporary directory: Read-only file system

runc state test_busybox (status=1):
time="2020-04-22T19:30:44Z" level=error msg="container \"test_busybox\" does not exist"
container "test_busybox" does not exist

runc --criu /usr/local/sbin/criu restore -d --work-path ./work-dir --console-socket /tmp/console.sock test_busybox (status=0):

(00.047787) mnt: Switching to new ns to clean ghosts
(00.050034) Unlock network
(00.050045) Running network-unlock scripts
(00.050048) 	RPC
iptables-restore: line 5 failed
(00.052202) Error (criu/util.c:610): exited, status=1
ip6tables-restore: line 5 failed
(00.054215) Error (criu/util.c:610): exited, status=1

runc state test_busybox (status=0):
{
  "ociVersion": "1.0.2",
  "id": "test_busybox",
  "pid": 58717,
  "status": "running",
  "bundle": "/tmp/busyboxtest",
  "rootfs": "/tmp/busyboxtest/rootfs",
  "created": "2020-04-22T19:30:44.825464731Z",
  "owner": ""
}
old network namespace inode 4026532171
new network namespace inode 4026532171

runc --criu /usr/local/sbin/criu checkpoint --work-path ./work-dir test_busybox (status=0):

runc state test_busybox (status=1):
time="2020-04-22T19:30:45Z" level=error msg="container \"test_busybox\" does not exist"
container "test_busybox" does not exist

runc --criu /usr/local/sbin/criu restore -d --work-path ./work-dir --console-socket /tmp/console.sock test_busybox (status=2):
unexpected fault address 0x0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x55f390d9501d]

goroutine 1 [running]:
runtime.throw(0x55f390f492cc, 0x5)
	/usr/lib/golang/src/runtime/panic.go:774 +0x74 fp=0xc000117d90 sp=0xc000117d60 pc=0x55f390b52934
runtime.sigpanic()
	/usr/lib/golang/src/runtime/signal_unix.go:401 +0x3e2 fp=0xc000117dc0 sp=0xc000117d90 pc=0x55f390b678d2
github.com/golang/protobuf/proto.(*unmarshalInfo).unmarshal(0xc0001b0000, 0xc00017e1c0, 0xc0001a4000, 0xa, 0xa000, 0x55f390b3118a, 0x20)
	/root/go/pkg/mod/github.com/golang/protobuf@v1.3.5/proto/table_unmarshal.go:173 +0x76d fp=0xc000117f90 sp=0xc000117dc0 pc=0x55f390d9501d
github.com/golang/protobuf/proto.(*InternalMessageInfo).Unmarshal(0xc0001801a0, 0x55f3911add40, 0xc00017e1c0, 0xc0001a4000, 0xa, 0xa000, 0xc0001ae001, 0x0)
	/root/go/pkg/mod/github.com/golang/protobuf@v1.3.5/proto/table_unmarshal.go:63 +0x68 fp=0xc000117ff0 sp=0xc000117f90 pc=0x55f390d94638
github.com/golang/protobuf/proto.(*Buffer).Unmarshal(0xc000118070, 0x55f3911add40, 0xc00017e1c0, 0x0, 0x0)
	/root/go/pkg/mod/github.com/golang/protobuf@v1.3.5/proto/decode.go:424 +0x1ee fp=0xc000118040 sp=0xc000117ff0 pc=0x55f390d72b4e
github.com/golang/protobuf/proto.Unmarshal(0xc0001a4000, 0xa, 0xa000, 0x55f3911add40, 0xc00017e1c0, 0x1000, 0x1000)
	/root/go/pkg/mod/github.com/golang/protobuf@v1.3.5/proto/decode.go:342 +0x172 fp=0xc0001180a8 sp=0xc000118040 pc=0x55f390d726b2
github.com/opencontainers/runc/libcontainer.(*linuxContainer).criuSwrk(0xc00015e1e0, 0x0, 0xc00018c000, 0x0, 0x7f1318338200, 0x0, 0x0, 0x0, 0x0, 0x0)
	/vagrant/libcontainer/container_linux.go:1580 +0xca5 fp=0xc0001184d0 sp=0xc0001180a8 pc=0x55f390eb8615
github.com/opencontainers/runc/libcontainer.(*linuxContainer).checkCriuVersion(0xc00015e1e0, 0x2906, 0x7f1318338228, 0xc000118638)
	/vagrant/libcontainer/container_linux.go:805 +0x1c9 fp=0xc000118580 sp=0xc0001184d0 pc=0x55f390eb17a9
github.com/opencontainers/runc/libcontainer.(*linuxContainer).Restore(0xc00015e1e0, 0xc0000a57c0, 0xc00014f5f0, 0x0, 0x0)
	/vagrant/libcontainer/container_linux.go:1260 +0xbd fp=0xc000118bd0 sp=0xc000118580 pc=0x55f390eb4fcd
main.(*runner).run(0xc000119490, 0xc00015e000, 0x0, 0x0, 0x0)
	/vagrant/utils_linux.go:322 +0x8d5 fp=0xc0001193d8 sp=0xc000118bd0 pc=0x55f390f3bf35
main.startContainer(0xc0000d0840, 0xc0000f0400, 0x3, 0xc00014f5f0, 0x0, 0x0, 0x0)
	/vagrant/utils_linux.go:462 +0x43c fp=0xc000119520 sp=0xc0001193d8 pc=0x55f390f3d0bc
main.glob..func12(0xc0000d0840, 0x0, 0xc000124300)
	/vagrant/restore.go:112 +0x115 fp=0xc000119588 sp=0xc000119520 pc=0x55f390f40065
github.com/urfave/cli.HandleAction(0x55f3910f4700, 0x55f39119a460, 0xc0000d0840, 0xc0000d0840, 0x0)
	/root/go/pkg/mod/github.com/urfave/cli@v1.22.1/app.go:523 +0xc0 fp=0xc0001195b0 sp=0xc000119588 pc=0x55f390efbfc0
github.com/urfave/cli.Command.Run(0x55f390f4b95c, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x55f390f5ffc3, 0x2e, 0x0, ...)
	/root/go/pkg/mod/github.com/urfave/cli@v1.22.1/command.go:174 +0x51e fp=0xc0001198d8 sp=0xc0001195b0 pc=0x55f390efcd2e
github.com/urfave/cli.(*App).Run(0xc000022380, 0xc0000200c0, 0xc, 0xc, 0x0, 0x0)
	/root/go/pkg/mod/github.com/urfave/cli@v1.22.1/app.go:276 +0x71a fp=0xc000119c20 sp=0xc0001198d8 pc=0x55f390efa06a
main.main()
	/vagrant/main.go:151 +0xb29 fp=0xc000119f60 sp=0xc000119c20 pc=0x55f390f348d9
runtime.main()
	/usr/lib/golang/src/runtime/proc.go:203 +0x226 fp=0xc000119fe0 sp=0xc000119f60 pc=0x55f390b542f6
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000119fe8 sp=0xc000119fe0 pc=0x55f390b80281

goroutine 7 [syscall]:
os/signal.signal_recv(0x55f3911ab4c0)
	/usr/lib/golang/src/runtime/sigqueue.go:147 +0x9e
os/signal.loop()
	/usr/lib/golang/src/os/signal/signal_unix.go:23 +0x24
created by os/signal.init.0
	/usr/lib/golang/src/os/signal/signal_unix.go:29 +0x43
(00.047787) mnt: Switching to new ns to clean ghosts
(00.050034) Unlock network
(00.050045) Running network-unlock scripts
(00.050048) 	RPC
iptables-restore: line 5 failed
(00.052202) Error (criu/util.c:610): exited, status=1
ip6tables-restore: line 5 failed
(00.054215) Error (criu/util.c:610): exited, status=1

runc state test_busybox (status=1):
time="2020-04-22T19:30:45Z" level=error msg="container \"test_busybox\" does not exist"
container "test_busybox" does not exist

runc list (status=0):
load container test_busybox: container "test_busybox" does not exist
ID          PID         STATUS      BUNDLE      CREATED     OWNER
```

**Comment by kolyshkin** [comment]
@adrianreber @avagin PTAL

**Comment by Snorch** [comment]
You have error when locking network:

```
iptables-restore: line 5 failed
```

Looks like some problem with "mark" rule:

```
        char conf[] =   "*filter\n"
                                ":CRIU - [0:0]\n"
                                "-I INPUT -j CRIU\n"
                                "-I OUTPUT -j CRIU\n"
>                                "-A CRIU -m mark --mark " __stringify(SOCCR_MARK) " -j ACCEPT\n"
                                "-A CRIU -j DROP\n"
                                "COMMIT\n";
```

So you should be able to reproduce it without criu with:

```
unshare -n
iptables -N CRIU
iptables -A CRIU -m mark --mark 0xC114 -j ACCEPT
```

My guess is that you either have some problem with kernel modules providing "mark" functionality or you have nft version of iptables-save, e.g. on my system iptables-save is non-nft:

iptables-save --version
iptables-save v1.8.3 (legacy)

**Comment by avagin** [comment]
criu doesn't fail if network_unlock fails.

**Comment by adrianreber** [comment]
As it happens somewhere in the protobuf code I would also blame protobuf at first. I have never seen this on my systems and I am also using Fedora 31 a lot as in this runc test case.

Looking at go.mod in runc protobuf was recently (2020-03-25) updated from 1.0.0 to 1.3.5.

**Comment by avagin** [comment]
> github.com/opencontainers/runc/libcontainer.(*linuxContainer).checkCriuVersion(0xc00015e1e0, 0x2906, 0x7f1318338228, 0xc000118638)

This is checkCriuVersion...

**Comment by kolyshkin** [comment]
@Snorch this is unrelated (we're talking about runc SEGV here), but

```console
[root@localhost vagrant]# ls -l /proc/self/ns/net 
lrwxrwxrwx. 1 root root 0 Apr 23 17:29 /proc/self/ns/net -> 'net:[4026531992]'
[root@localhost vagrant]# unshare -n
[root@localhost vagrant]# ls -l /proc/self/ns/net 
lrwxrwxrwx. 1 root root 0 Apr 23 17:30 /proc/self/ns/net -> 'net:[4026532533]'
[root@localhost vagrant]# iptables -N CRIU
[root@localhost vagrant]# iptables -A CRIU -m mark --mark 0xC114 -j ACCEPT
[root@localhost vagrant]# exit
logout
[root@localhost vagrant]# uname -a
Linux localhost.localdomain 5.3.7-301.fc31.x86_64 #1 SMP Mon Oct 21 19:18:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
[root@localhost vagrant]# iptables --version
iptables v1.8.3 (legacy)
```

**Comment by avagin** [comment]
> @Snorch this is unrelated (we're talking about runc SEGV here), but

It fails because we don't call network_lock if a container is running in the host net namespace.

**Comment by kolyshkin** [comment]
Hmm, I meant to file this for runc not criu. Can close now I guess.

**Comment by kolyshkin** [comment]
got a sigsegv in a very different place but same environment: https://github.com/opencontainers/runc/pull/2342#issuecomment-619286382

that one is also a nil pointer dereference, but in json rather than protobuf. Both are using reflect I guess...

**Comment by kolyshkin** [comment]
Anyway I guess this has nothing to do with criu and I never meant to file it as a criu bug.

**Comment by Snorch** [comment]
> @Snorch this is unrelated (we're talking about runc SEGV here), but
> 
> ```
> [root@localhost vagrant]# ls -l /proc/self/ns/net 
> lrwxrwxrwx. 1 root root 0 Apr 23 17:29 /proc/self/ns/net -> 'net:[4026531992]'
> [root@localhost vagrant]# unshare -n
> [root@localhost vagrant]# ls -l /proc/self/ns/net 
> lrwxrwxrwx. 1 root root 0 Apr 23 17:30 /proc/self/ns/net -> 'net:[4026532533]'
> [root@localhost vagrant]# iptables -N CRIU
> [root@localhost vagrant]# iptables -A CRIU -m mark --mark 0xC114 -j ACCEPT
> [root@localhost vagrant]# exit
> logout
> [root@localhost vagrant]# uname -a
> Linux localhost.localdomain 5.3.7-301.fc31.x86_64 #1 SMP Mon Oct 21 19:18:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
> [root@localhost vagrant]# iptables --version
> iptables v1.8.3 (legacy)
> ```

Yes you are right, I misread network-**un**lock though the problem was on lock side, sorry.
