### ISSUE TITLE
The test crit-recode.py fails for certain image files

### ISSUE THREAD

**Issue by adrianreber** [checkpoint-restore/criu#1393]
There is a Jenkins error that shows crit-recode failures:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/base64.py", line 510, in _input_type_check
    m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./test/crit-recode.py", line 25, in recode_and_check
    r_img = pycriu.images.dumps(pb)
  File "/var/lib/jenkins/workspace/CRIU_CRIU-crit_criu-dev-DBNKUFN2EIV77FCLF3JCP2VBDOBGR7GVBO3FUACODQLMNTD7X6AQ/test/pycriu/images/images.py", line 635, in dumps
    dump(img, f)
  File "/var/lib/jenkins/workspace/CRIU_CRIU-crit_criu-dev-DBNKUFN2EIV77FCLF3JCP2VBDOBGR7GVBO3FUACODQLMNTD7X6AQ/test/pycriu/images/images.py", line 626, in dump
    handler.dump(img['entries'], f)
  File "/var/lib/jenkins/workspace/CRIU_CRIU-crit_criu-dev-DBNKUFN2EIV77FCLF3JCP2VBDOBGR7GVBO3FUACODQLMNTD7X6AQ/test/pycriu/images/images.py", line 289, in dump
    f.write(base64.decodebytes(item['extra']))
  File "/usr/lib/python3.8/base64.py", line 545, in decodebytes
    _input_type_check(s)
  File "/usr/lib/python3.8/base64.py", line 513, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./test/crit-recode.py", line 66, in <module>
    if not recode_and_check(imgf, o_img, False):
  File "./test/crit-recode.py", line 27, in recode_and_check
    r_img = pycriu.images.dumps(pb)
  File "/var/lib/jenkins/workspace/CRIU_CRIU-crit_criu-dev-DBNKUFN2EIV77FCLF3JCP2VBDOBGR7GVBO3FUACODQLMNTD7X6AQ/test/pycriu/images/images.py", line 635, in dumps
    dump(img, f)
  File "/var/lib/jenkins/workspace/CRIU_CRIU-crit_criu-dev-DBNKUFN2EIV77FCLF3JCP2VBDOBGR7GVBO3FUACODQLMNTD7X6AQ/test/pycriu/images/images.py", line 626, in dump
    handler.dump(img['entries'], f)
  File "/var/lib/jenkins/workspace/CRIU_CRIU-crit_criu-dev-DBNKUFN2EIV77FCLF3JCP2VBDOBGR7GVBO3FUACODQLMNTD7X6AQ/test/pycriu/images/images.py", line 272, in dump
    item = entries.pop(0)
IndexError: pop from empty list
```

We are running crit-recode.py also during pull requests but the image files are missing certain sections which trigger this error, because we currently do this:
```
./test/zdtm.py run -t zdtm/static/env00 -k always
./test/crit-recode.py
```
It this is changed to:
```
./test/zdtm.py run -t zdtm/static/env00 -t zdtm/transition/fork -k always
./test/crit-recode.py
```
It will fail with:
```
Traceback (most recent call last):
  File "/usr/lib64/python3.9/base64.py", line 510, in _input_type_check
    m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/criu/./test/crit-recode.py", line 25, in recode_and_check
    r_img = pycriu.images.dumps(pb)
  File "/home/criu/test/pycriu/images/images.py", line 635, in dumps
    dump(img, f)
  File "/home/criu/test/pycriu/images/images.py", line 626, in dump
    handler.dump(img['entries'], f)
  File "/home/criu/test/pycriu/images/images.py", line 147, in dump
    pb2dict.dict2pb(entry, pbuff)
  File "/home/criu/test/pycriu/images/pb2dict.py", line 442, in dict2pb
    dict2pb(value, getattr(pb, field.name, None))
  File "/home/criu/test/pycriu/images/pb2dict.py", line 442, in dict2pb
    dict2pb(value, getattr(pb, field.name, None))
  File "/home/criu/test/pycriu/images/pb2dict.py", line 432, in dict2pb
    dict2pb(v, pb_val.add())
  File "/home/criu/test/pycriu/images/pb2dict.py", line 444, in dict2pb
    setattr(pb, field.name, _dict2pb_cast(field, value))
  File "/home/criu/test/pycriu/images/pb2dict.py", line 369, in _dict2pb_cast
    return get_bytes_dec(field)(value)
  File "/home/criu/test/pycriu/images/pb2dict.py", line 253, in decode_base64
    return base64.decodebytes(value)
  File "/usr/lib64/python3.9/base64.py", line 537, in decodebytes
    _input_type_check(s)
  File "/usr/lib64/python3.9/base64.py", line 513, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.9/base64.py", line 510, in _input_type_check
    m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/criu/./test/crit-recode.py", line 66, in <module>
    if not recode_and_check(imgf, o_img, False):
  File "/home/criu/./test/crit-recode.py", line 27, in recode_and_check
    r_img = pycriu.images.dumps(pb)
  File "/home/criu/test/pycriu/images/images.py", line 635, in dumps
    dump(img, f)
  File "/home/criu/test/pycriu/images/images.py", line 626, in dump
    handler.dump(img['entries'], f)
  File "/home/criu/test/pycriu/images/images.py", line 147, in dump
    pb2dict.dict2pb(entry, pbuff)
  File "/home/criu/test/pycriu/images/pb2dict.py", line 442, in dict2pb
    dict2pb(value, getattr(pb, field.name, None))
  File "/home/criu/test/pycriu/images/pb2dict.py", line 442, in dict2pb
    dict2pb(value, getattr(pb, field.name, None))
  File "/home/criu/test/pycriu/images/pb2dict.py", line 432, in dict2pb
    dict2pb(v, pb_val.add())
  File "/home/criu/test/pycriu/images/pb2dict.py", line 444, in dict2pb
    setattr(pb, field.name, _dict2pb_cast(field, value))
  File "/home/criu/test/pycriu/images/pb2dict.py", line 369, in _dict2pb_cast
    return get_bytes_dec(field)(value)
  File "/home/criu/test/pycriu/images/pb2dict.py", line 253, in decode_base64
    return base64.decodebytes(value)
  File "/usr/lib64/python3.9/base64.py", line 537, in decodebytes
    _input_type_check(s)
  File "/usr/lib64/python3.9/base64.py", line 513, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not str
```
I think this is still a left-over from the Python 2 to Python 3 switch. From what I have seen it seems that there are protobuf fields of the type `bytes` which are not correctly handled during decode and encode.

**Comment by minhbq-99** [comment]
This line makes the error

https://github.com/checkpoint-restore/criu/blob/49b9cff74563b556059b804199da136bab855c3c/lib/py/images/pb2dict.py#L367

As I see, this is from a commit https://github.com/checkpoint-restore/criu/commit/49b9cff74563b556059b804199da136bab855c3c to handle json encoding. I think this can fix the error
```
def _dict2pb_cast(field, value):
    if field.type == FD.TYPE_BYTES:
        return get_bytes_dec(field)(value.encode())
```

**Comment by adrianreber** [comment]
@minhbq-99 Thanks for your help. Please have a look at #1414 which should have fixed this. Jenkins is no longer complaining and this can actually be closed.

Please let us know if my fix could be improved.
