### ISSUE TITLE
When name is null, it will coredump

### ISSUE THREAD

**Issue by yinshuisiquan** [checkpoint-restore/criu#1412]
https://github.com/checkpoint-restore/criu/blob/c8beca65580da87b89964da3ffb454ca99aa6bc6/criu/sk-unix.c#L1277
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help" .
Type "apropos word" to search for commands related to "word" ...
Reading symbols from /usr/sboin/criu..Reading sywbols fron /usr/lib/debug/.build-id/b4/8507ab6614613facdcc8b7edeb1a948a54e550.debug...done.
done.
[New LWP 132]
[New LwP 215]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by 'criu restore --images-dir /host/nsr/checkpoints/pt-26210316_154236 -v4 -j --tcp'.
Program terminated with signal SIGSEGV，Segmentation fault.
#0  0x00005646bbc96a3a in prep_unix_sk_cwd(ui=ui@entry=0x7f76e85bda50, prev_cwd_fd=prev_cwd_fd@entry=0x7fff390bfedc, prev_root_fd=prev_root_fd@entry=0x7fff390bfee0, prev_mntns_fd=prev_mntns_fd@entry=0x7fff390bfee4) at criu/sk-unix.c:1197
1197   criu/sk-unix.c: No such file or directory.
[Current thread is 1 (LWP 132)]
(gdb) bt
#0  0x00005646bbc96a3a in prep_unix_sk_cwd(ui=ui@entry=0x7f76e85bda50, prev_cwd_fd=prev_cwd_fd@entry=0x7fff390bfedc, prev_root_fd=prev_root_fd@entry=0x7fff390bfee0, prev_mntns_fd=prev_mntns_fd@entry=0x7fff390bfee4) at criu/sk-unix.c:1197
#1  0x00005646bbc99d77 in post_open_standalone (fd=18，d=0x7f76e85bdb88) at criu/sk-unix.c:1308
#2  open_unixsk standalone (new_fd=coptimized out>,ui=x7f76e85bdb40) at criu/sk-unix.c:1800
#3  open_unix_sk(d=0x7f76e85bdb88，new_fd=<optimized out>) at criu/sk-unix.c:1960
#4  0x00005646bbc51469 in open_fd (fle=0x7f76e85b7800) at criu/files.c:1157
#5  open_fdinfos (me=0x7f76e85e62b8)at criu/files.c:1213
#6  prepare_fds (me=0x7f76e85e62b8) at criu/files.c:1321
#7  Gx0085646bbc433e in restore_one_ alive task(pid=132，core=core@entry=0x5646bd392e18) at criu/cr-restore.c:904
#8  0x60005646bbc428ed in restore_one_task (core=0x5646bd392e10，pid=<optimized out>) at criu/cr-restore.c:1274
#9  restore_task with children (_arg=0x7fff390c0610) at criu/cr-restore.c:1948
#10 0x00007f76e7316d0f in clone () from /lib/x86_64-linux-gnu/libc.so.6
(gdb)

**Comment by Snorch** [comment]
You should provide full criu logs and coredump + binary or reproduce.

Looking on the code a bit, I can't get how peer of standalone socket can have zero ->name pointer. To be able to create "standalone" socket with peer, one need to connect to a listening unix socket AFAICS. To be able to connect the listening socket should be bind to some address which would be it's name. And after accept new peer socket is created copying the name from the listening socket...

Probably I'm missing something...

@mihalicyn @cyrillos please also take a look.

**Comment by yinshuisiquan** [comment]
When the server in the container, and the client outside the container, and I use criu in the container, it will be happened
