### ISSUE TITLE
Restored JVM process died silently

### ISSUE THREAD

**Issue by zl-wang** [checkpoint-restore/criu#1429]
This particular exercise was carried out on RHEL8.3 ppc64le:

I rebuilt JDK which is not using systemcfg file anymore, in order to avoid the non-checkpointable situation described here: #1425 .  Now, I can both checkpoint it and restore it successfully (according to the criu log files). However, I either cannot see the restored java process running (ps -ef|grep java  ... no show, that is), or sometimes i can see it alive but just die silently when I curl to ping it (supposed to respond the same).  No other output whatsoever to know why it died.  Tail of the dump.log:

(00.065423) Dumping pstree (pid: 1825601)
(00.065426) ----------------------------------------
(00.065428) Process: 1825601(1825601)
(00.065465) ----------------------------------------
(00.065537) cg: All tasks in criu's cgroups. Nothing to dump.
(00.065539) unix: Dumping external sockets
(00.065547) unix: 	Dumping extern: ino 5190844 peer_ino 1442227 family    1 type    1 state  1 name /var/lib/sss/pipes/nss
(00.065553) unix: 	Dumped extern: id 0x145 ino 5190844 peer 0 type 2 state 10 name 23 bytes
(00.065557) unix: Found ino 1442227 in exception unix sk list
(00.065559) unix: found exception for unix name-less external socket.
(00.065563) unix: 	Dumped: id 0xb2 ino 1442227 peer 5190844 type 1 state 1 name 0 bytes
(00.065568) Writing image inventory (version 1)
(00.065668) Running post-dump scripts
(00.065671) Unfreezing tasks into 2
(00.065673) 	Unseizing 1825601 into 2
(00.068127) Writing stats
(00.068242) Dumping finished successfully

Tail of the restore.log:

(00.040256) 1825603 was trapped
(00.040259) 1825603 (native) is going to execute the syscall 221, required is 172
(00.040283) 1825601 was trapped
(00.040286) 1825601 (native) is going to execute the syscall 91, required is 172
(00.040292) 1825605 was trapped
(00.040295) 1825605 (native) is going to execute the syscall 172, required is 172
(00.040304) 1825605 was stopped
(00.040307) 1825601 was trapped
(00.040310) 1825601 (native) is going to execute the syscall 172, required is 172
(00.040318) 1825601 was stopped
(00.040322) 1825603 was trapped
(00.040325) 1825603 (native) is going to execute the syscall 172, required is 172
(00.040333) 1825603 was stopped
(00.040352) 1825601 was trapped
(00.040355) 1825601 (native) is going to execute the syscall 91, required is 91
(00.040395) 1825601 was stopped
(00.040401) Running pre-resume scripts
(00.040535) Restore finished successfully. Tasks resumed.
(00.040537) Writing stats
(00.040733) Running post-resume scripts

is the mis-matched syscall above (e.g. exec 91, requiring 172) a legitimate concern?

any tip or insight is appreciated ...

**Comment by adrianreber** [comment]
Do you see any messages in the journal or dmesg?

Please attach the complete log files.

**Comment by adrianreber** [comment]
I also see `/var/lib/sss/pipes/nss` mentioned in above log files. For our CI runs we always disable the sssd service to not have that socket be problematic during checkpointing. Although this looks like it is not related to sssd.

**Comment by zl-wang** [comment]
[
[restore.log](https://github.com/checkpoint-restore/criu/files/6236433/restore.log)
](url)

@adrianreber  here it is.

**Comment by zl-wang** [comment]
i did see a few messages in dmesg:
`[Tue Mar 30 13:36:56 2021] Default Executo[1815308]: unhandled signal 5 at 00007fff6a90b13c nip 00007fff6a90b13c lr 00007fff6a9a6848 code 1
[Tue Mar 30 13:42:40 2021] Default Executo[1816094]: unhandled signal 5 at 00007fff6a90b13c nip 00007fff6a90b13c lr 00007fff6a9a6848 code 1
[Tue Mar 30 14:10:06 2021] Default Executo[1825825]: unhandled signal 5 at 00007fff8acf643c nip 00007fff8acf643c lr 00007fff8ad99708 code 1
[Tue Mar 30 14:11:25 2021] Default Executo[1857615]: unhandled signal 5 at 00007fff8acf643c nip 00007fff8acf643c lr 00007fff8ad99708 code 1
[Tue Mar 30 14:14:27 2021] Default Executo[1937483]: unhandled signal 5 at 00007fff8acf643c nip 00007fff8acf643c lr 00007fff8ad99708 code 1`

looks like SIGTRAP.  Wondering what code 1 means.

**Comment by adrianreber** [comment]
Hmm, could this be an altivec problem?

Did you try a simple process (without altivec)?

**Comment by zl-wang** [comment]
the JVM build was indeed enabling altivec, but i expected only a very few limited places are using vector instructions.  could you say more about this?  did current criu on ppc not support client processes using vector instructions? 

I will try a simpler app later ...

**Comment by adrianreber** [comment]
> the JVM build was indeed enabling altivec, but i expected only a very few limited places are using vector instructions. could you say more about this? did current criu on ppc not support client processes using vector instructions?

CRIU should support altivec. But maybe there is a bug somehwere. Our testing has a process which is supposed to use altivec, but maybe something is missing in the test which the JVM does. It was just a guess. We also run tests on ppc64le but there are lesser tests on ppc64le than on x86_64. So maybe something is not working as expected. Or maybe never was. Or maybe our ppc64le test system is too old. Something.

> I will try a simpler app later ...

Sounds good.

**Comment by zl-wang** [comment]
The bug appeared to be that the signal handler(s) are not correctly restored.  At least, when I disabled trap-instruction generation by the JIT compiler, now i can do checkpoint/restore JVM successfully. Not sure it is particular to SIGTRAP or all signals though.

**Comment by avagin** [comment]
You can run your app under strace and see how it sets up signal handlers.  Than you can run criu restore under strace and see how it restores signal handlers.

**Comment by zl-wang** [comment]
@avagin   i enabled trap instr generation by the JIT compiler, and ran the test as you suggested.  using:
strace -e trace=signal -o output-file  <command>

app under strace, i only saw:
```
rt_sigaction(SIGRTMIN, {sa_handler=0x7cb5c24071b0, sa_mask=[], sa_flags=SA_SIGINFO}, NULL, 8) = 0
rt_sigaction(SIGRT_1, {sa_handler=0x7cb5c24072c0, sa_mask=[], sa_flags=SA_RESTART|SA_SIGINFO}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
```

strace the restore, i saw:
```
rt_sigaction(SIGRTMIN, {sa_handler=0x7cb5c24071b0, sa_mask=[], sa_flags=SA_SIGINFO}, NULL, 8) = 0
rt_sigaction(SIGRT_1, {sa_handler=0x7cb5c24072c0, sa_mask=[], sa_flags=SA_RESTART|SA_SIGINFO}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
rt_sigaction(SIGPIPE, {sa_handler=SIG_IGN, sa_mask=[PIPE], sa_flags=SA_RESTART}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGCHLD, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGCHLD, {sa_handler=0x93488f16aa0, sa_mask=[CHLD], sa_flags=SA_RESTART|SA_SIGINFO|SA_NOCLDSTOP}, NULL, 8) = 0
rt_sigprocmask(SIG_SETMASK, ~[CHLD RTMIN RT_1], NULL, 8) = 0
rt_sigaction(SIGCHLD, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, NULL, 8) = 0
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_STOPPED, si_pid=43860, si_uid=0, si_status=0, si_utime=1, si_stime=4} ---
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_STOPPED, si_pid=43863, si_uid=0, si_status=0, si_utime=0, si_stime=0} ---
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_STOPPED, si_pid=43865, si_uid=0, si_status=0, si_utime=0, si_stime=0} ---
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_STOPPED, si_pid=43874, si_uid=0, si_status=0, si_utime=0, si_stime=0} ---
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_STOPPED, si_pid=43875, si_uid=0, si_status=0, si_utime=0, si_stime=0} ---
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_STOPPED, si_pid=43876, si_uid=0, si_status=0, si_utime=0, si_stime=0} ---
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_STOPPED, si_pid=43877, si_uid=0, si_status=0, si_utime=0, si_stime=0} ---
<long list of SIGCHLD>
```

JVM is restored, but pinging it killed it:  curl -s -o /dev/null -w '%{http_code}' localhost:9080/pingperf/ping/greeting
silently, didn't see the killing SIGTRAP in strace output, but i did see dmesg -T as follows:
```
[Wed Apr  7 15:24:56 2021] Default Executo[43927]: unhandled trap (5) at 74c6e44f9550 nip 74c6e44f9550 lr 74c6fb14e6b8 code 1
[Wed Apr  7 15:24:56 2021] Default Executo[43927]: code: 606374c6 786307c6 6463f416 60632db8 80630000 2c030000 40820074 e86e0020
[Wed Apr  7 15:24:56 2021] Default Executo[43927]: code: 80430008 08820000 80020004 8063000c <7cc01808> 78630fc8 38630008 7c63122e
```
7cc01808 is indeed a trap instruction.

**Comment by zl-wang** [comment]
it looked like:   `rt_sigprocmask(SIG_SETMASK, ~[CHLD RTMIN RT_1], NULL, 8) = 0`
is the problem? not sure though.

**Comment by avagin** [comment]
I am able to reproduce this issue on powerpc. I tried the same steps on x86_64 and everything works fine.

**Comment by avagin** [comment]
Here are /proc/pid/status before and after C/R:
https://gist.github.com/avagin/4d6f6314ecf213afacacfd8dd0274836

before: 2000000181005cdf
after:    2000000181005ccf

**Comment by avagin** [comment]
I have one idea what can be a reason for this issue. Could you try out this patch:
```
diff --git a/compel/src/lib/infect.c b/compel/src/lib/infect.c
index 1bb07ace5..65366669d 100644
--- a/compel/src/lib/infect.c
+++ b/compel/src/lib/infect.c
@@ -447,6 +447,7 @@ static int parasite_run(pid_t pid, int cmd, unsigned long ip, void *stack,
        k_rtsigset_t block;
 
        ksigfillset(&block);
+       block.sig[0] = block.sig[0] & ~(1<<(SIGTRAP - 1));
        if (ptrace(PTRACE_SETSIGMASK, pid, sizeof(k_rtsigset_t), &block)) {
                pr_perror("Can't block signals for %d", pid);
                goto err_sig;
```

**Comment by zl-wang** [comment]
@avagin  it doesn't work.  it still silently died.  dmesg -T showed same:
```
[Thu Apr  8 08:47:14 2021] Default Executo[43951]: unhandled trap (5) at 74c6e44f9550 nip 74c6e44f9550 lr 74c6fb14e6b8 code 1
[Thu Apr  8 08:47:14 2021] Default Executo[43951]: code: 606374c6 786307c6 6463f416 60632db8 80630000 2c030000 40820074 e86e0020
[Thu Apr  8 08:47:14 2021] Default Executo[43951]: code: 80430008 08820000 80020004 8063000c <7cc01808> 78630fc8 38630008 7c63122e
```

After restoring, i am seeing a different status though:  (hopefully  this gave some hints)
`SigCgt:	20000001810044ed`

**Comment by zl-wang** [comment]
i started the app independently (not restoring).  i am seeing this status:  (equivalent to before checking)
`SigCgt:	20000001810044fd`

still 1-bit difference.  Could it be that the fix is not applied to the right mask?

**Comment by avagin** [comment]
> @avagin it doesn't work. it still silently died. dmesg -T showed same:

@zl-wang are you sure that you applied the patch, recompiled CRIU, and used a new binary? I am asking because I reproduced this issue locally and I see that the sigtrap action is restored correctly with this patch.

> After restoring, i am seeing a different status though: (hopefully this gave some hints)
> SigCgt: 20000001810044ed



0x10 is SIGTRAP.

**Comment by avagin** [comment]
@zl-wang could you try to run this test:

* git fetch origin b15d8e8687d87de371d59987e07b17e7f6ad511f
* git checkout b15d8e8687d87de371d59987e07b17e7f6ad511f
* make
* make -C test/zdtm/static/env00
* make -C 
* python test/zdtm.py run -t zdtm/static/env00  -f h

**Comment by zl-wang** [comment]
i did make the changes, and i saw a different size of executable criu (than before).  as a matter of fact, i ran into:

```
root@pjavaubun02:/home/zlwang/criu# git checkout b15d8e8687d87de371d59987e07b17e7f6ad511f
error: Your local changes to the following files would be overwritten by checkout:
	compel/src/lib/infect.c       <<<  that SIGTRAP change
	criu/proc_parse.c              <<<  that systemcfg change
Please commit your changes or stash them before you switch branches.
Aborting
```

**Comment by avagin** [comment]
> root@pjavaubun02:/home/zlwang/criu# git checkout b15d8e8687d87de371d59987e07b17e7f6ad511f

could you clone criu sources in a new directory and try to run the test there?

**Comment by zl-wang** [comment]
clone in a new directory, and do exactly the above.  choke on:
```
  LINK     lib/c/libcriu.so
  LINK     lib/c/libcriu.a
  GEN      lib/py/images/magic.py
root@pjavaubun02:/home/zlwang/criu# make -C test/zdtm/static/env00
make: *** test/zdtm/static/env00: No such file or directory.  Stop.
```

**Comment by avagin** [comment]
$ make -C test/zdtm/static/ env00

**Comment by zl-wang** [comment]
make -C running into error (needing a directory argument).  then, (hopefully is what you are looking for)
```
root@pjavaubun02:/home/zlwang/criu# python3 test/zdtm.py run -t zdtm/static/env00  -f h
Traceback (most recent call last):
  File "test/zdtm.py", line 26, in <module>
    import pycriu as crpc
  File "/home/zlwang/criu/test/pycriu/__init__.py", line 1, in <module>
    from . import rpc_pb2 as rpc
  File "/home/zlwang/criu/test/pycriu/rpc_pb2.py", line 6, in <module>
    from google.protobuf.internal import enum_type_wrapper
ModuleNotFoundError: No module named 'google'
```

**Comment by avagin** [comment]
you need to install python-protobuf

**Comment by avagin** [comment]
It looks like you have protobuf for python3:
$ python3 test/zdtm.py run -t zdtm/static/env00  -f h

**Comment by zl-wang** [comment]
that package looks like independent of 3 or not.  python3 runs with same result:
```
root@pjavaubun02:/home/zlwang/criu# python3 test/zdtm.py run -t zdtm/static/env00  -f h
Traceback (most recent call last):
  File "test/zdtm.py", line 26, in <module>
    import pycriu as crpc
  File "/home/zlwang/criu/test/pycriu/__init__.py", line 1, in <module>
    from . import rpc_pb2 as rpc
  File "/home/zlwang/criu/test/pycriu/rpc_pb2.py", line 6, in <module>
    from google.protobuf.internal import enum_type_wrapper
ModuleNotFoundError: No module named 'google'
```

**Comment by avagin** [comment]
you can try to apply this patch:
```
diff --git a/test/zdtm.py b/test/zdtm.py
index 9488c6edb..6a2560e94 100755
--- a/test/zdtm.py
+++ b/test/zdtm.py
@@ -23,8 +23,6 @@ import tempfile
 import time
 from builtins import (input, int, open, range, str, zip)
 
-import pycriu as crpc
-
 import yaml
 
 os.chdir(os.path.dirname(os.path.abspath(__file__)))
@@ -1201,6 +1199,7 @@ class criu:
                           self.__stats_file(action)]).wait()
 
     def check_pages_counts(self):
+        return
         if not os.access(self.__stats_file("dump"), os.R_OK):
             return
 
```

**Comment by zl-wang** [comment]
with that ...
```
root@pjavaubun02:/home/zlwang/criu# python test/zdtm.py run -t zdtm/static/env00  -f h
cc -D_GNU_SOURCE    umount2.c   -o umount2
cc -D_GNU_SOURCE    zdtm_ct.c   -o zdtm_ct
userns is supported
=== Run 1/1 ================ zdtm/static/env00
timens isn't supported on 5.4.0-70-generic
========================== Run zdtm/static/env00 in h ==========================
Start test
./env00 --pidfile=env00.pid --outfile=env00.out --envname=ENV_00_TEST
Run criu dump
=[log]=> dump/zdtm/static/env00/54/1/dump.log
------------------------ grep Error ------------------------
b'(00.025690)'
b'(00.025696) Dumping core for thread (pid: 55)'
b'(00.025703) ----------------------------------------'
b'(00.025710) Dumping GP/FPU registers for 55'
b'(00.025717) Warn  (compel/arch/ppc64/src/lib/infect.c:333): Will restore 55 with interrupted system call'
------------------------ ERROR OVER ------------------------
Run criu restore
Send the 15 signal to  54
Wait for zdtm/static/env00(54) to die for 0.100000
Removing dump/zdtm/static/env00/54
========================= Test zdtm/static/env00 PASS ==========================
```

**Comment by zl-wang** [comment]
@avagin  thanks for the help.
i did:  make clean, then make, and make install
now it looked like it is working.  this morning, i changed the code, and didn't do a make clean.

```
root@pjavaubun02:/home/zlwang/criu-ol# for i in 1 2 3 4 5 6 7 8 9 0; do curl -s -o /dev/null -w '%{http_code}' localhost:9080/pingperf/ping/greeting; echo; done
200
200
200
200
200
200
200
200
200
200

```

**Comment by zl-wang** [comment]
@avagin  i assumed you will check these improvements in.

**Comment by avagin** [comment]
The workaround has been merged. Now we need to figure out how to fix the problem properly.

**Comment by zl-wang** [comment]
@avagin   I am at the tip of criu-dev:  commit d34c7cee8614f5eeb9a58546f7867a1dafb67200 (HEAD -> criu-dev, upstream/criu-dev)
                 build it:  make clean/make/make install
                 SIGTRAP is still not caught, as shown in the dmesg:
```
[1462374.250144] Default Executo[4071288]: unhandled trap (5) at 7bc17850c450 nip 7bc17850c450 lr 7bc18e44e6b8 code 1
[1462374.250162] Default Executo[4071288]: code: 60637bc1 786307c6 64638816 60632dc8 80630000 2c030000 40820074 e86e0020
[1462374.250171] Default Executo[4071288]: code: 80430008 08820000 80020004 8063000c <7cc01808> 78630fc8 38630008 7c63122e
```

is that expected?  I am sure it contains your work-around commit:   
```
commit 8063eb8fe64148efdc1d0c8d73eee38ff92b9b57
Author: Andrei Vagin <avagin@gmail.com>
Date:   Thu May 20 19:32:53 2021 +0300

    parasite: don't block SIGTRAP

    This is the workaround for #1429.
```

**Comment by avagin** [comment]
This is my mistake:
```
diff --git a/compel/include/uapi/ksigset.h b/compel/include/uapi/ksigset.h
index 8b5d95804..e2465041d 100644
--- a/compel/include/uapi/ksigset.h
+++ b/compel/include/uapi/ksigset.h
@@ -26,6 +26,6 @@ static inline void ksigaddset(k_rtsigset_t *set, int _sig)
 static inline void ksigdelset(k_rtsigset_t *set, int _sig)
 {
        int sig = _sig - 1;
-       set->sig[sig / _NSIG_BPW] |= ~(1UL << (sig % _NSIG_BPW));
+       set->sig[sig / _NSIG_BPW] &= ~(1UL << (sig % _NSIG_BPW));
 }
 #endif
```

I will create a pr with this fix.

**Comment by 0x7f454c46** [comment]
Ah, I should've noticed it in review.
An exercise on attentiveness :)
I thought you've copy'n'pasted this from an existing function (not `ksigaddset()`) and missed it.
