### ISSUE TITLE
`make test ` from source raises error: Exception: The kernel is tainted: '512\n'

### ISSUE THREAD

**Issue by glassxer1** [checkpoint-restore/criu#1439]
OS: Ubuntu 20.04
When following the instruction on "https://criu.org/How_to_submit_patches", I ran `make test` to test my changes. But then I have this error 
`
make zdtm
./zdtm.py run -a --parallel 2
The kernel is tainted: '512\n'
Traceback (most recent call last):
  File "./zdtm.py", line 2685, in <module>
    opts['action'](opts)
  File "./zdtm.py", line 2283, in run_tests
    launcher = Launcher(opts, len(torun))
  File "./zdtm.py", line 1935, in __init__
    raise Exception("The kernel is tainted: %r" % self.__taint)
Exception: The kernel is tainted: '512\n'
make[2]: *** [Makefile:23: zdtm] Error 1
make[1]: *** [Makefile:7: all] Error 2
make: *** [Makefile:326: test] Error 2
`
I know that I can get away with it when I run zdtm.py with `--ignore-taint`, but is there any way that I can get rid of this error when doing `make test`?

**Comment by avagin** [comment]
@glassxer1 you need to look at the kernel log why the kernel is tainted. It isn't normal.

**Comment by glassxer1** [comment]
I think this could be caused by the broken kernel of Ubuntu and some third-party libraries. I will post here if I have any confirmation.

**Comment by rst0git** [comment]
https://www.kernel.org/doc/html/v5.9/admin-guide/tainted-kernels.html
