### ISSUE TITLE
Cirrus CI / Vagrant Fedora Rawhide based test fails

### ISSUE THREAD

**Issue by avagin** [checkpoint-restore/criu#2468]
```
+ make uninstall DESTDIR=/criu/test/others/make/test.install-2452444
make[1]: Entering directory '/criu'
fatal: detected dubious ownership in repository at '/criu'
To add an exception for this directory, call:

	git config --global --add safe.directory /criu
Note: Building with amdgpu_plugin.
fatal: detected dubious ownership in repository at '/criu'
To add an exception for this directory, call:

	git config --global --add safe.directory /criu
 UNINSTALL crit.1 criu-ns.1 compel.1 criu-amdgpu-plugin.1
 UNINSTALL criu.8
 UNINSTALL libcriu.so
 UNINSTALL pkgconfig/criu.pc
 UNINSTALL pycriu
Traceback (most recent call last):
  File "/criu/./scripts/uninstall_module.py", line 65, in <module>
    uninstall_module(args.module_name, args.prefix)
  File "/criu/./scripts/uninstall_module.py", line 41, in uninstall_module
    dist_info_path = str(importlib_metadata.distribution(package_name)._path)
  File "/usr/lib/python3.13/site-packages/importlib_metadata/__init__.py", line 961, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.13/site-packages/importlib_metadata/__init__.py", line 392, in from_name
    return next(iter(cls._prefer_valid(cls.discover(name=name))))
  File "/usr/lib/python3.13/site-packages/importlib_metadata/_itertools.py", line 152, in _get_values
    item_value = self._key(item)
  File "/usr/lib/python3.13/site-packages/importlib_metadata/__init__.py", line 423, in <lambda>
    buckets = bucket(dists, lambda dist: bool(dist.metadata))
  File "/usr/lib/python3.13/site-packages/importlib_metadata/__init__.py", line 455, in metadata
    from . import _adapters
  File "/usr/lib/python3.13/site-packages/importlib_metadata/_adapters.py", line 3, in <module>
    import email.message
  File "/usr/lib64/python3.13/email/message.py", line 11, in <module>
    import quopri
ModuleNotFoundError: No module named 'quopri'
make[2]: *** [lib/Makefile:75: uninstall] Error 1
make[1]: *** [Makefile.install:89: uninstall] Error 2
make[1]: Leaving directory '/criu'
make: *** [Makefile:4: run] Error 2
make: Leaving directory '/criu/test/others/make'
+ cleanup_cgroup
+ ./test/zdtm_umount_cgroups 1
make: Leaving directory '/vagrant/criu/scripts/ci'
make: *** [Makefile:51: fedora-rawhide] Error 2
make: *** [Makefile:73: vagrant-fedora-rawhide] Error 2
make: Leaving directory '/tmp/criu/scripts/ci'

Exit status: 2
```
https://github.com/checkpoint-restore/criu/pull/2466/checks?check_run_id=28865055570

**Comment by rst0git** [comment]
It looks like this error is caused by changes in [version 8.1.0](https://github.com/python/importlib_metadata/compare/v8.0.0...v8.1.0) of the `importlib_metadata` module.
(version 8.0.0 works as expected)
```
sudo pip3 install importlib_metadata==8.1.0
make uninstall PREFIX=/usr
...
 UNINSTALL pycriu
Traceback (most recent call last):
  File "/home/radostin/Projects/criu/./scripts/uninstall_module.py", line 65, in <module>
    uninstall_module(args.module_name, args.prefix)
  File "/home/radostin/Projects/criu/./scripts/uninstall_module.py", line 41, in uninstall_module
    dist_info_path = str(importlib_metadata.distribution(package_name)._path)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/importlib_metadata/__init__.py", line 960, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/importlib_metadata/__init__.py", line 391, in from_name
    return next(iter(cls._prefer_valid(cls.discover(name=name))))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/importlib_metadata/_itertools.py", line 152, in _get_values
    item_value = self._key(item)
                 ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/importlib_metadata/__init__.py", line 422, in <lambda>
    buckets = bucket(dists, lambda dist: bool(dist.metadata))
                                              ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/importlib_metadata/__init__.py", line 454, in metadata
    from . import _adapters
  File "/usr/local/lib/python3.12/site-packages/importlib_metadata/_adapters.py", line 3, in <module>
    import email.message
  File "/usr/lib64/python3.12/email/message.py", line 11, in <module>
    import quopri
ModuleNotFoundError: No module named 'quopri'
make[1]: *** [lib/Makefile:75: uninstall] Error 1
make: *** [Makefile.install:89: uninstall] Error 2
```
