### ISSUE TITLE
session04 hans up

### ISSUE THREAD

**Issue by avagin** [checkpoint-restore/criu#361]
```
 2221 ?        S      0:00  |                                           \_ python2 zdtm.py
 2239 ?        S      0:03  |                                               \_ python2 zdtm.py
 2926 ?        Ss     0:00  |                                                   \_ ./session04 --pidfile=session04.pid --outfile=session04.out
 3029 ?        S      0:00  |                                                       \_ ./session04 --pidfile=session04.pid --outfile=session04.out
 3048 ?        Ss     0:00  |                                                           \_ ./session04 --pidfile=session04.pid --outfile=session04.out
 3052 ?        S      0:00  |                                                               \_ ./session04 --pidfile=session04.pid --outfile=session04.out
 3067 ?        S      0:00  |                                                               |   \_ ./session04 --pidfile=session04.pid --outfile=session04.out
 3053 ?        S      0:00  |                                                               \_ ./session04 --pidfile=session04.pid --outfile=session04.out
 3061 ?        Ss     0:00  |                                                               |   \_ ./session04 --pidfile=session04.pid --outfile=session04.out
 3055 ?        Ss     0:00  |                                                               \_ ./session04 --pidfile=session04.pid --outfile=session04.out
 3056 ?        Ss     0:00  |                                                               \_ ./session04 --pidfile=session04.pid --outfile=session04.out
 3059 ?        Ss     0:00  |                                                               \_ ./session04 --pidfile=session04.pid --outfile=session04.out
 3063 ?        S      0:00  |                                                               |   \_ ./session04 --pidfile=session04.pid --outfile=session04.out
 3064 ?        S      0:00  |                                                               |   \_ ./session04 --pidfile=session04.pid --outfile=session04.out
 3076 ?        S      0:00  |                                                               |       \_ ./session04 --pidfile=session04.pid --outfile=session04.out
 3062 ?        Ss     0:00  |                                                               \_ ./session04 --pidfile=session04.pid --outfile=session04.out
 3066 ?        S      0:00  |                                                               |   \_ ./session04 --pidfile=session04.pid --outfile=session04.out
 3070 ?        Ss     0:00  |                                                               \_ ./session04 --pidfile=session04.pid --outfile=session04.out
 3075 ?        S      0:00  |                                                                   \_ ./session04 --pidfile=session04.pid --outfile=session04.out
```

```
[root@zdtm ~]# gdb -p 3029
(gdb) bt
#0  0x00007fec8d264230 in __read_nocancel () from target:/lib64/libc.so.6
#1  0x0000000000402492 in handle_command () at session04.c:181
#2  mainloop () at session04.c:63
#3  clone_func (_arg=<optimized out>) at session04.c:81
#4  0x00007fec8d274d0f in clone () from target:/lib64/libc.so.6

[root@zdtm ~]# cat /proc/3075/cwd/session04.out
08:55:23.667:     5:   0: Hello. My pid is 5
08:55:23.667:     5:   0: fork(1, 20000000) = 6
08:55:23.668:     1:   1: Hello. My pid is 1
08:55:23.668:     1:   1: setsid()
08:55:23.668:     1:   1: fork(2, 0) = 2
08:55:23.668:     2:   2: Hello. My pid is 2
08:55:23.668:     2:   2: setsid()
08:55:23.669:     2:   2: fork(3, 0) = 3
08:55:23.669:     3:   3: Hello. My pid is 3
08:55:23.669:     3:   3: fork(4, 0) = 4
08:55:23.669:     3:   3: setsid()
08:55:23.669:     2:   2: die()
08:55:23.670:     1:   1: wait(2) = 2
08:55:23.670:     1:   1: fork(5, 0) = 5
08:55:23.670:     5:   5: Hello. My pid is 5
08:55:23.670:     5:   5: fork(6, 0) = 6
08:55:23.671:     4:   4: Hello. My pid is 4
08:55:23.671:     6:   6: Hello. My pid is 6
08:55:23.671:     6:   6: setsid()
08:55:23.671:     6:   6: fork(7, 0) = 7
08:55:23.671:     7:   7: Hello. My pid is 7
08:55:23.672:     7:   7: fork(8, 0) = 8
08:55:23.672:     8:   8: Hello. My pid is 8
08:55:23.672:     8:   8: fork(9, 0) = 9
08:55:23.672:     8:   8: setsid()
08:55:23.672:     7:   7: die()
08:55:23.673:     6:   6: wait(7) = 7
08:55:23.673:     1:   1: fork(10, 0) = 10
08:55:23.673:    10:  10: Hello. My pid is 10
08:55:23.673:    10:  10: setsid()
08:55:23.674:    10:  10: fork(11, 0) = 11
08:55:23.674:     9:   9: Hello. My pid is 9
08:55:23.674:    11:  11: Hello. My pid is 11
08:55:23.674:    11:  11: fork(12, 0) = 12
08:55:23.674:    12:  12: Hello. My pid is 12
08:55:23.675:    12:  12: fork(13, 0) = 13
08:55:23.675:    12:  12: setsid()
08:55:23.675:    12:  12: fork(14, 20000000) = 14
08:55:23.676:     1:   1: fork(15, 0) = 15
08:55:23.676:    15:  15: Hello. My pid is 15
08:55:23.676:    15:  15: setsid()
08:55:23.676:    15:  15: setns(14, 536870912) = 14
08:55:23.676:    13:  13: Hello. My pid is 13
08:55:23.677:     1:  14: Hello. My pid is 1
08:55:23.791:    15:  15: fork(16, 0) = 16
08:55:23.792:     2:  16: Hello. My pid is 2
08:55:23.792:     2:  16: fork(17, 0) = 3
08:55:23.792:    11:  11: die()
08:55:23.793:    10:  10: wait(11) = 11
08:55:23.793:     2:  16: die()
08:55:23.793:    15:  15: wait(16) = 16
08:55:23.793:     1:   1: fork(18, 20000000) = 18
08:55:23.793:    15:  15: setns(18, 536870912) = 18
08:55:23.794:     3:  17: Hello. My pid is 3
08:55:23.803:     1:  18: Hello. My pid is 1
08:55:23.805:    15:  15: fork(19, 0) = 19
08:55:23.829:     2:  19: Hello. My pid is 2
08:55:23.830:     2:  19: fork(20, 0) = 3
08:55:23.830:     2:  19: die()
08:55:23.830:    15:  15: wait(19) = 19
08:55:23.830:     5:   0: getsid()
08:55:23.830:     1:   1: getsid()
08:55:23.830:     3:   3: getsid()
08:55:23.830:     4:   4: getsid()
08:55:23.831:     5:   5: getsid()
08:55:23.831:     6:   6: getsid()
08:55:23.831:     8:   8: getsid()
08:55:23.831:     9:   9: getsid()
08:55:23.831:    10:  10: getsid()
08:55:23.831:    12:  12: getsid()
08:55:23.831:    13:  13: getsid()
08:55:23.831:     1:  14: getsid()
08:55:23.831:    15:  15: getsid()
08:55:23.832:     3:  17: getsid()
08:55:23.835:     3:  20: Hello. My pid is 3
08:55:23.904:     1:  18: getsid()
08:55:23.944:     3:  20: getsid()
08:55:30.580:     5:   0: getsid()
08:55:30.580:     1:   1: getsid()
08:55:30.580:     3:   3: getsid()
08:55:30.581:     4:   4: getsid()
08:55:30.581:     5:   5: getsid()
08:55:30.581:     6:   6: getsid()
08:55:30.581:     8:   8: getsid()
08:55:30.581:     9:   9: getsid()
08:55:30.582:    10:  10: getsid()
08:55:30.582:    12:  12: getsid()
08:55:30.582:    13:  13: getsid()
08:55:30.582:     1:  14: getsid()
08:55:30.582:    15:  15: getsid()
08:55:30.583:     3:  17: getsid()
08:55:30.583:     1:  18: getsid()
08:55:30.583:     3:  20: getsid()
08:55:30.583:     4: PASS
```
Cc: @Snorch

**Comment by Snorch** [comment]
same as https://github.com/xemul/criu/issues/372 ?
