### ISSUE TITLE
criu pre-dump hangs

### ISSUE THREAD

**Issue by avagin** [checkpoint-restore/criu#432]
https://ci.openvz.org/job/CRIU/job/CRIU-lazy-remote/job/criu-dev/283/

```

 1080 ?        Ss     0:00  \_ sshd: root [priv]
 1088 ?        S      2:41  |   \_ sshd: root@notty
 1144 ?        Ssl   25:50  |       \_ java -jar slave.jar
 7206 ?        S      0:00  |           \_ /bin/sh -xe /tmp/jenkins5237358498461213084.sh
 7210 ?        S      0:00  |               \_ /bin/sh ./test/jenkins/run_ct sh -c mount --make-rprivate / && mount --rbind . /mnt && cd /mnt &&  ./test/jenkins/criu-remote-lazy-pages.sh
 7214 ?        S      0:00  |                   \_ unshare --mount --pid --fork -- /var/lib/jenkins/workspace/U_CRIU-lazy-remote_criu-dev-ANWJTDWDDZPPQKLOWVTEZ5H7GWDM35WJ4IVMP6D3GK3QGZ4RLM4Q
 7215 ?        S      0:00  |                       \_ sh -c mount --make-rprivate / && mount --rbind . /mnt && cd /mnt &&  ./test/jenkins/criu-remote-lazy-pages.sh
14675 ?        S      0:01  |                           \_ python2 ./test/zdtm.py run --all --keep-going --report report --parallel 4 --remote-lazy-pages --pre 2 -x cmdlinenv00 -x maps02
29409 ?        S      0:00  |                               \_ ./zdtm_ct zdtm.py
29410 ?        S      0:00  |                                   \_ python2 zdtm.py
29412 ?        S      0:00  |                                       \_ python2 zdtm.py
29581 ?        S      0:00  |                                       |   \_ ../criu/criu pre-dump --no-default-config -o pre-dump.log -D dump/zdtm/static/file_locks02/159/1 -v4 -t 159 --file-
29576 ?        Ss     0:00  |                                       \_ ./file_locks02 --pidfile=file_locks02.pid --outfile=file_locks02.out --filename=file_locks02.test
29579 ?        ts     0:00  |                                           \_ ./file_locks02 --pidfile=file_locks02.pid --outfile=file_locks02.out --filename=file_locks02.test
29580 ?        t      0:00  |                                               \_ ./file_locks02 --pidfile=file_locks02.pid --outfile=file_locks02.out --filename=file_locks02.test

[root@zdtm ~]# nsenter -p -m -t 14675
[root@zdtm /]# ps axf
  PID TTY      STAT   TIME COMMAND
21484 pts/0    S      0:00 -bash
21503 pts/0    R+     0:00  \_ ps axf
    1 ?        S      0:00 sh -c mount --make-rprivate / && mount --rbind . /mnt && cd /mnt &&  ./test/jenkins/criu-remote-lazy-pages.sh
 6958 ?        S      0:01 python2 ./test/zdtm.py run --all --keep-going --report report --parallel 4 --remote-lazy-pages --pre 2 -x cmdlinenv00 -x maps02
21310 ?        S      0:00  \_ ./zdtm_ct zdtm.py
21311 ?        S      0:00      \_ python2 zdtm.py
21313 ?        S      0:00          \_ python2 zdtm.py
21482 ?        S      0:00          |   \_ ../criu/criu pre-dump --no-default-config -o pre-dump.log -D dump/zdtm/static/file_locks02/159/1 -v4 -t 159 --file-locks --pidfile /mnt/test/zdtm/s
21477 ?        Ss     0:00          \_ ./file_locks02 --pidfile=file_locks02.pid --outfile=file_locks02.out --filename=file_locks02.test
21480 ?        ts     0:00              \_ ./file_locks02 --pidfile=file_locks02.pid --outfile=file_locks02.out --filename=file_locks02.test
21481 ?        t      0:00                  \_ ./file_locks02 --pidfile=file_locks02.pid --outfile=file_locks02.out --filename=file_locks02.test
[root@zdtm /]# ps axf
  PID TTY      STAT   TIME COMMAND
  165 ?        S      0:00 -bash
  185 ?        R+     0:00  \_ ps axf
    1 ?        S      0:00 python2 zdtm.py
    3 ?        S      0:00 python2 zdtm.py
  164 ?        S      0:00  \_ ../criu/criu pre-dump --no-default-config -o pre-dump.log -D dump/zdtm/static/file_locks02/159/1 -v4 -t 159 --file-locks --pidfile /mnt/test/zdtm/static/file_l
  159 ?        Ss     0:00 ./file_locks02 --pidfile=file_locks02.pid --outfile=file_locks02.out --filename=file_locks02.test
  162 ?        ts     0:00  \_ ./file_locks02 --pidfile=file_locks02.pid --outfile=file_locks02.out --filename=file_locks02.test
  163 ?        t      0:00      \_ ./file_locks02 --pidfile=file_locks02.pid --outfile=file_locks02.out --filename=file_locks02.test


(gdb) bt
#0  0x00007fba90931e3a in wait4 () from /lib64/libc.so.6
#1  0x00000000004a83f4 in parasite_fini_seized (ctl=0x1be1180) at compel/src/lib/infect.c:1227
#2  compel_stop_daemon (ctl=0x1be1180) at compel/src/lib/infect.c:1286
#3  0x00000000004a8e62 in compel_cure_remote (ctl=ctl@entry=0x1be1180) at compel/src/lib/infect.c:1301
#4  0x000000000043daa2 in pre_dump_one_task (item=0x1bdc920) at criu/cr-dump.c:1297
#5  cr_pre_dump_tasks (pid=pid@entry=159) at criu/cr-dump.c:1700
#6  0x0000000000425ad3 in main (argc=<optimized out>, argv=0x7ffe64f55888, envp=<optimized out>) at criu/crtools.c:1013
(gdb) frame 1
#1  0x00000000004a83f4 in parasite_fini_seized (ctl=0x1be1180) at compel/src/lib/infect.c:1227
1227		if (wait4(pid, &status, __WALL, NULL) != pid) {
(gdb) p pid
$1 = 159
(gdb) p *ctl
$2 = {rpid = 159, remote_map = 0x7fc8bb07e000, local_map = 0x7fba91cd1000, sigreturn_addr = 0x7fc8bb0813a0, map_length = 61440, ictx = {sock = 4, save_regs = 0x4a1920 <save_task_regs>, 
    make_sigframe = 0x477560 <make_sigframe>, regs_arg = 0x1bdec40, task_size = 140737488351232, syscall_ip = 4194304, flags = 12, child_handler = 0x477580 <sigchld_handler>, 
    orig_handler = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {65536, 0 <repeats 15 times>}}, sa_flags = 268435460, sa_restorer = 0x0}, 
    open_proc = 0x49d480 <do_open_proc>, log_fd = 1048575}, daemonized = true, orig = {sigmask = {sig = {0}}, regs = {{native = {r15 = 0, r14 = 0, r13 = 140737038045760, r12 = 0, 
          bp = 140737038054314, bx = 4294967295, r11 = 582, r10 = 0, r9 = 0, r8 = 0, ax = 202, cx = 140500102914265, dx = 0, si = 0, di = 6317144, orig_ax = 202, ip = 140500102914263, 
          cs = 51, flags = 582, sp = 140737037782808, ss = 43, fs_base = 140500108105536, gs_base = 0, ds = 0, es = 0, fs = 0, gs = 0}, compat = {bx = 0, cx = 0, dx = 0, si = 0, 
          di = 3844657728, bp = 32767, ax = 0, ds = 0, es = 3844666282, fs = 32767, gs = 4294967295, orig_ax = 0, ip = 582, cs = 0, flags = 0, sp = 0, ss = 0}}, __is_native = 10}}, 
  rstack = 0x7fc8bb08cac0, sigframe = 0x7fba91cdb000, rsigframe = 0x7fc8bb088000, r_thread_stack = 0x0, parasite_ip = 140500108042288, addr_cmd = 0x7fba91cd1050, 
  addr_args = 0x7fba91cd5b18, args_size = 20480, tsock = 5, pblob = {parasite_type = 1, {hdr = {mem = 0x4e1ec0 <parasite_blob>, bsize = 19222, nr_gotpcrel = 0, parasite_ip_off = 48, 
        addr_cmd_off = 80, addr_arg_off = 19224, relocs = 0x72af60 <parasite_relocs>, nr_relocs = 3}}}}

[root@zdtm /]# cat /proc/159/stack 
[<ffffffff9d760ecf>] __skb_wait_for_more_packets+0x11f/0x170
[<ffffffff9d8366ed>] unix_dgram_recvmsg+0xcd/0x530
[<ffffffff9d836b6d>] unix_seqpacket_recvmsg+0x1d/0x30
[<ffffffff9d74e32d>] sock_recvmsg+0x3d/0x50
[<ffffffff9d74ee54>] SYSC_recvfrom+0xe4/0x160
[<ffffffff9d7511fe>] SyS_recvfrom+0xe/0x10
[<ffffffff9d8c4d37>] entry_SYSCALL_64_fastpath+0x1a/0xa5
[<ffffffffffffffff>] 0xffffffffffffffff

[root@zdtm /]# tail -n 80 /proc/164/fd/1048575 
(00.003113) page-pipe: 		0x400000 1
(00.003115) page-pipe: 		0x605000 2
(00.003116) page-pipe: 	buf 1 pages, 1 iovs, flags: 1 pipe_off: 3 :
(00.003117) page-pipe: 		0x12c8000 1
(00.003119) page-pipe: 	buf 6 pages, 1 iovs, flags: 0 pipe_off: 4 :
(00.003120) page-pipe: 		0x7fc8bae61000 6
(00.003121) page-pipe: 	buf 6 pages, 4 iovs, flags: 1 pipe_off: a :
(00.003123) page-pipe: 		0x7fc8bae67000 2
(00.003124) page-pipe: 		0x7fc8bae6a000 1
(00.003125) page-pipe: 		0x7fc8bb08d000 2
(00.003127) page-pipe: 		0x7fc8bb090000 1
(00.003128) page-pipe: 	buf 2 pages, 1 iovs, flags: 0 pipe_off: 10 :
(00.003129) page-pipe: 		0x7fc8bb092000 2
(00.003131) page-pipe: 	buf 7 pages, 4 iovs, flags: 1 pipe_off: 12 :
(00.003139) page-pipe: 		0x7fc8bb094000 1
(00.003141) page-pipe: 		0x7fffe524b000 3
(00.003142) page-pipe: 		0x7fffe528c000 2
(00.003144) page-pipe: 		0x7fffe528f000 1
(00.003145) page-pipe: 	buf 2 pages, 1 iovs, flags: 0 pipe_off: 19 :
(00.003146) page-pipe: 		0x7fffe52bc000 2
(00.003148) page-pipe: * 0 holes:
(00.003149) PPB: 3 pages 2 segs 16 pipe 0 off
(00.003175) Sent msg to daemon 66 0 0
(00.003192) Wait for ack 66 on daemon socket
pie: 1: __fetched msg: 66 0 0
pie: 1: __sent ack msg: 66 66 0
pie: 1: Daemon waits for command
(00.003244) Fetched ack: 66 66 0
(00.003252) PPB: 1 pages 1 segs 16 pipe 2 off
(00.003279) Sent msg to daemon 66 0 0
pie: 1: __fetched msg: 66 0 0
(00.003296) Wait for ack 66 on daemon socket
pie: 1: __sent ack msg: 66 66 0
pie: 1: Daemon waits for command
(00.003322) Fetched ack: 66 66 0
(00.003328) PPB: 6 pages 1 segs 16 pipe 3 off
(00.003352) Sent msg to daemon 66 0 0
pie: 1: __fetched msg: 66 0 0
(00.003368) Wait for ack 66 on daemon socket
pie: 1: __sent ack msg: 66 66 0
pie: 1: Daemon waits for command
(00.003394) Fetched ack: 66 66 0
(00.003400) PPB: 6 pages 4 segs 32 pipe 4 off
(00.003426) Sent msg to daemon 66 0 0
(00.003442) Wait for ack 66 on daemon socket
pie: 1: __fetched msg: 66 0 0
pie: 1: __sent ack msg: 66 66 0
pie: 1: Daemon waits for command
(00.003496) Fetched ack: 66 66 0
(00.003504) PPB: 2 pages 1 segs 32 pipe 8 off
(00.003530) Sent msg to daemon 66 0 0
pie: 1: __fetched msg: 66 0 0
(00.003546) Wait for ack 66 on daemon socket
pie: 1: __sent ack msg: 66 66 0
pie: 1: Daemon waits for command
(00.003572) Fetched ack: 66 66 0
(00.003578) PPB: 7 pages 4 segs 32 pipe 9 off
(00.003603) Sent msg to daemon 66 0 0
pie: 1: __fetched msg: 66 0 0
(00.003620) Wait for ack 66 on daemon socket
pie: 1: __sent ack msg: 66 66 0
pie: 1: Daemon waits for command
(00.003661) Fetched ack: 66 66 0
(00.003668) PPB: 2 pages 1 segs 32 pipe 13 off
(00.003695) Sent msg to daemon 66 0 0
(00.003710) Wait for ack 66 on daemon socket
pie: 1: __fetched msg: 66 0 0
pie: 1: __sent ack msg: 66 66 0
pie: 1: Daemon waits for command
(00.003766) Fetched ack: 66 66 0
(00.003774) Reset 159's dirty tracking
(00.003802)  ... done
(00.003810) ----------------------------------------
(00.003838) Sent msg to daemon 65 0 0
(00.003847) Wait for ack 65 on daemon socket
pie: 1: __fetched msg: 65 0 0
(00.003974) Fetched ack: 65 65 0
(00.004025) Waiting for 159 to trap
pie: 1: __sent ack msg: 65 65 0
pie: 1: Daemon waits for command
```

Cc: @rppt

**Comment by avagin** [comment]
```
        /* Start to trace syscalls for each thread */
        if (ptrace(PTRACE_INTERRUPT, pid, NULL, NULL)) {
                pr_perror("Unable to interrupt the process");
                return -1;
        }

        pr_debug("Waiting for %d to trap\n", pid);
        if (wait4(pid, &status, __WALL, NULL) != pid) {
                pr_perror("Waited pid mismatch (pid: %d)", pid);
                return -1;
        }
```

**Comment by avagin** [comment]
```
[root@zdtm mnt]# cat /proc/159/status | grep Sig
SigQ:	0/7371
SigPnd:	0000000000000000
SigBlk:	fffffffffffbfeff
SigIgn:	0000000001001000
SigCgt:	0000000000014000
[root@zdtm mnt]# cat /proc/164/status | grep Sig
SigQ:	2/7371
SigPnd:	0000000000000000
SigBlk:	0000000000000004
SigIgn:	0000000001001000
SigCgt:	0000000180002000
```
