### ISSUE TITLE
criu killed by SIGABRT

### ISSUE THREAD

**Issue by avagin** [checkpoint-restore/criu#487]
```
id 0f7c0eb5758cd3ba2da077705ca5318b3b30b68f
reason:         criu killed by SIGABRT
time:           Thu 17 May 2018 01:35:02 AM CEST
cmdline:        ../criu/criu lazy-pages -o lazy-pages.log -D dump/zdtm/transition/fork/855/3 -v4 --page-server --port 12345 --status-fd 4
uid:            0 (root)
count:          1
Directory:      /var/spool/abrt/ccpp-2018-05-17-01:35:02.929369-30803
Reported:       mailto:avagin@openvz.org
```

```
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fbd60209e4b in raise () from /lib64/libpthread.so.0
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.27-8.fc28.x86_64 libnet-1.1.6-15.fc28.x86_64 libnl3-3.4.0-3.fc28.x86_64 libselinux-2.7-13.fc28.x86_64 pcre2-10.31-4.fc28.x86_64 protobuf-c-1.3.0-4.fc28.x86_64
(gdb) bt
#0  0x00007fbd60209e4b in raise () from /lib64/libpthread.so.0
#1  0x000000000046a57f in page_server_async_read (f=<optimized out>) at criu/page-xfer.c:1180
#2  0x0000000000494045 in epoll_run_rfds (epollfd=epollfd@entry=4, evs=evs@entry=0x1d88880, nr_fds=nr_fds@entry=47, timeout=timeout@entry=-1) at criu/util.c:1428
#3  0x0000000000491431 in handle_requests (nr_fds=47, events=0x1d88880, epollfd=4) at criu/uffd.c:1227
#4  cr_lazy_pages (daemon=<optimized out>) at criu/uffd.c:1442
#5  0x0000000000421b84 in main (argc=<optimized out>, argv=0x7ffcf70be868, envp=<optimized out>) at criu/crtools.c:780
(gdb)
```

**Comment by avagin** [comment]
@rppt Mike, it is the master branch. Let me know if this issue was fixed by the last your series.

**Comment by avagin** [comment]
https://patchwork.criu.org/series/2552/
