### ISSUE TITLE
Migrated TCP connection restores, but application does not resume correctly

### ISSUE THREAD

**Issue by dav-ell** [checkpoint-restore/criu#489]
`tcpdump` captured on host `192.168.1.105`, with a client migrating from `192.168.1.132` to `192.168.1.148`:
```
16:47:23.884798 IP (tos 0x0, ttl 64, id 18945, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.1.105.5672 > 192.168.1.132.34824: Flags [.], cksum 0x8464 (incorrect -> 0x949f), seq 2398472698, ack 1774775146, win 1463, options [nop,nop,TS val 607705647 ecr 3735039692], length 0
16:47:23.901372 IP (tos 0x0, ttl 64, id 24254, offset 0, flags [DF], proto TCP (6), length 117)
    192.168.1.132.34824 > 192.168.1.105.5672: Flags [P.], cksum 0x9348 (correct), seq 1774775146:1774775211, ack 2398472698, win 1455, options [nop,nop,TS val 3735039753 ecr 607705647], length 65
16:47:23.943096 IP (tos 0x0, ttl 64, id 18946, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.1.105.5672 > 192.168.1.132.34824: Flags [.], cksum 0x8464 (incorrect -> 0x93e4), seq 2398472698, ack 1774775211, win 1463, options [nop,nop,TS val 607705708 ecr 3735039753], length 0
16:47:23.962130 IP (tos 0x0, ttl 64, id 24255, offset 0, flags [DF], proto TCP (6), length 117)
    192.168.1.132.34824 > 192.168.1.105.5672: Flags [P.], cksum 0x9246 (correct), seq 1774775211:1774775276, ack 2398472698, win 1455, options [nop,nop,TS val 3735039813 ecr 607705708], length 65
16:47:24.006104 IP (tos 0x0, ttl 64, id 18947, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.1.105.5672 > 192.168.1.132.34824: Flags [.], cksum 0x8464 (incorrect -> 0x932a), seq 2398472698, ack 1774775276, win 1463, options [nop,nop,TS val 607705769 ecr 3735039813], length 0
16:47:24.024266 IP (tos 0x0, ttl 64, id 24256, offset 0, flags [DF], proto TCP (6), length 117)
    192.168.1.132.34824 > 192.168.1.105.5672: Flags [P.], cksum 0x918d (correct), seq 1774775276:1774775341, ack 2398472698, win 1455, options [nop,nop,TS val 3735039875 ecr 607705769], length 65
16:47:24.273766 IP (tos 0x0, ttl 64, id 24257, offset 0, flags [DF], proto TCP (6), length 312)
    192.168.1.132.34824 > 192.168.1.105.5672: Flags [P.], cksum 0x55bb (correct), seq 1774775341:1774775601, ack 2398472698, win 1455, options [nop,nop,TS val 3735040122 ecr 607705769], length 260
16:47:24.515165 IP (tos 0x0, ttl 64, id 24258, offset 0, flags [DF], proto TCP (6), length 377)
    192.168.1.132.34824 > 192.168.1.105.5672: Flags [P.], cksum 0x9963 (correct), seq 1774775276:1774775601, ack 2398472698, win 1455, options [nop,nop,TS val 3735040366 ecr 607705769], length 325
16:47:25.007122 IP (tos 0x0, ttl 64, id 24259, offset 0, flags [DF], proto TCP (6), length 377)
    192.168.1.132.34824 > 192.168.1.105.5672: Flags [P.], cksum 0x9777 (correct), seq 1774775276:1774775601, ack 2398472698, win 1455, options [nop,nop,TS val 3735040858 ecr 607705769], length 325


16:47:29.364939 IP (tos 0x0, ttl 64, id 55077, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.1.148.34824 > 192.168.1.105.5672: Flags [.], cksum 0x8c93 (correct), seq 1774775275, ack 2398472698, win 1455, options [nop,nop,TS val 3735041207 ecr 0], length 0
16:47:29.499503 IP (tos 0x0, ttl 64, id 55078, offset 0, flags [DF], proto TCP (6), length 637)
    192.168.1.148.34824 > 192.168.1.105.5672: Flags [P.], cksum 0x86bd (incorrect -> 0x36fe), seq 1774775601:1774776186, ack 2398472698, win 1455, options [nop,nop,TS val 3735041342 ecr 0], length 585
16:47:29.656134 IP (tos 0x0, ttl 64, id 58833, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.1.105.5672 > 192.168.1.148.34824: Flags [.], cksum 0x8474 (incorrect -> 0x9fe2), seq 2398472697, ack 1774775276, win 1463, options [nop,nop,TS val 607706056 ecr 0], length 0
16:47:29.656444 IP (tos 0x0, ttl 64, id 55080, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.1.148.34824 > 192.168.1.105.5672: Flags [.], cksum 0x87e0 (correct), seq 1774776186, ack 2398472698, win 1455, options [nop,nop,TS val 3735041499 ecr 0], length 0
16:47:29.711571 IP (tos 0x0, ttl 64, id 55081, offset 0, flags [DF], proto TCP (6), length 377)
    192.168.1.148.34824 > 192.168.1.105.5672: Flags [P.], cksum 0x9391 (correct), seq 1774775276:1774775601, ack 2398472698, win 1455, options [nop,nop,TS val 3735041554 ecr 0], length 325
16:47:29.711626 IP (tos 0x0, ttl 64, id 58834, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.1.105.5672 > 192.168.1.148.34824: Flags [.], cksum 0x8474 (incorrect -> 0x89b4), seq 2398472698, ack 1774775601, win 1461, options [nop,nop,TS val 607706111 ecr 3735041554], length 0
16:47:29.712164 IP (tos 0x0, ttl 64, id 55082, offset 0, flags [DF], proto TCP (6), length 637)
    192.168.1.148.34824 > 192.168.1.105.5672: Flags [P.], cksum 0x86bd (incorrect -> 0x35f2), seq 1774775601:1774776186, ack 2398472698, win 1455, options [nop,nop,TS val 3735041554 ecr 607706111], length 585
16:47:29.712180 IP (tos 0x0, ttl 64, id 58835, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.1.105.5672 > 192.168.1.148.34824: Flags [.], cksum 0x8474 (incorrect -> 0x876e), seq 2398472698, ack 1774776186, win 1457, options [nop,nop,TS val 607706112 ecr 3735041554], length 0
16:47:29.754302 IP (tos 0x0, ttl 64, id 58836, offset 0, flags [DF], proto TCP (6), length 86)
    192.168.1.105.5672 > 192.168.1.148.34824: Flags [P.], cksum 0x8496 (incorrect -> 0x30e8), seq 2398472698:2398472732, ack 1774776186, win 1463, options [nop,nop,TS val 607706154 ecr 3735041554], length 34
```

The relevant bit is:
```
16:47:25.007122 IP (tos 0x0, ttl 64, id 24259, offset 0, flags [DF], proto TCP (6), length 377)
    192.168.1.132.34824 > 192.168.1.105.5672: Flags [P.], cksum 0x9777 (correct), seq 1774775276:1774775601, ack 2398472698, win 1455, options [nop,nop,TS val 3735040858 ecr 607705769], length 325

16:47:29.364939 IP (tos 0x0, ttl 64, id 55077, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.1.148.34824 > 192.168.1.105.5672: Flags [.], cksum 0x8c93 (correct), seq 1774775275, ack 2398472698, win 1455, options [nop,nop,TS val 3735041207 ecr 0], length 0
```
Especially the **`seq 1774775276:1774775601`** before the checkpoint on host `192.168.1.132` and **`seq 1774775275`** after the restore on host `192.168.1.148`. The sequence number appears to be off by 1.

The TCP connection did not continue correctly in this case. After migrating back to `192.168.1.132` it worked again, even in the state it was in (included in the log -- it was off by 1 on that migration also).

Log: [failed-tcp-dump.txt](https://github.com/checkpoint-restore/criu/files/2019818/failed-tcp-dump.txt)

**Comment by avagin** [comment]
I need tcp image files to investigate this issue.

**Comment by avagin** [comment]
Why do you think that this connection didn't continue correctly? From tcp dump, we see that it transfer data in both directions.
```
    192.168.1.148.34824 > 192.168.1.105.5672: Flags [P.], cksum 0x9391 (correct), seq 1774775276:1774775601, ack 2398472698, win 1455, options [nop,nop,TS val 3735041554 ecr 0], length 325
```

**Comment by dav-ell** [comment]
> Why do you think that this connection didn't continue correctly? From tcp dump, we see that it's transfering data in both directions.

Shortly after the section I posted from the tcpdump, the applications send `[P.]` repeatedly back and forth to each other, then don't communicate with each other for 30 seconds, then send a single message, then don't do anything again until I migrate the client back to the original host it came from.

If I let the client and server stay in the state that they are in after sending `[P.]` repeatedly, then the client and server will eventually disconnect, usually with a `unexpected close` error. I agree that it's odd that communication actually does resume, but it breaks the migration for them to resume incorrectly.

```
    192.168.1.148.34824 > 192.168.1.105.5672: Flags [P.], cksum 0x6671 (correct), seq 1774776186:1774776219, ack 2398472732, win 1455, options [nop,nop,TS val 3735041597 ecr 607706154], length 33
16:47:29.755182 IP (tos 0x0, ttl 64, id 58837, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.1.105.5672 > 192.168.1.148.34824: Flags [.], cksum 0x8474 (incorrect -> 0x86cf), seq 2398472732, ack 1774776219, win 1463, options [nop,nop,TS val 607706155 ecr 3735041597], length 0
16:47:29.755481 IP (tos 0x0, ttl 64, id 58838, offset 0, flags [DF], proto TCP (6), length 86)
    192.168.1.105.5672 > 192.168.1.148.34824: Flags [P.], cksum 0x8496 (incorrect -> 0x3079), seq 2398472732:2398472766, ack 1774776219, win 1463, options [nop,nop,TS val 607706155 ecr 3735041597], length 34
16:47:29.755865 IP (tos 0x0, ttl 64, id 55086, offset 0, flags [DF], proto TCP (6), length 85)
    192.168.1.148.34824 > 192.168.1.105.5672: Flags [P.], cksum 0x662c (correct), seq 1774776219:1774776252, ack 2398472766, win 1455, options [nop,nop,TS val 3735041598 ecr 607706155], length 33
16:47:29.762337 IP (tos 0x0, ttl 64, id 58839, offset 0, flags [DF], proto TCP (6), length 86)
    192.168.1.105.5672 > 192.168.1.148.34824: Flags [P.], cksum 0x8496 (incorrect -> 0x302e), seq 2398472766:2398472800, ack 1774776252, win 1463, options [nop,nop,TS val 607706162 ecr 3735041598], length 34
16:47:29.763007 IP (tos 0x0, ttl 64, id 55087, offset 0, flags [DF], proto TCP (6), length 85)
    192.168.1.148.34824 > 192.168.1.105.5672: Flags [P.], cksum 0x65db (correct), seq 1774776252:1774776285, ack 2398472800, win 1455, options [nop,nop,TS val 3735041605 ecr 607706162], length 33
16:47:29.763452 IP (tos 0x0, ttl 64, id 58840, offset 0, flags [DF], proto TCP (6), length 86)
    192.168.1.105.5672 > 192.168.1.148.34824: Flags [P.], cksum 0x8496 (incorrect -> 0x2fe3), seq 2398472800:2398472834, ack 1774776285, win 1463, options [nop,nop,TS val 607706163 ecr 3735041605], length 34
16:47:29.763841 IP (tos 0x0, ttl 64, id 55088, offset 0, flags [DF], proto TCP (6), length 85)

[P.]'s continue...

   192.168.1.148.34824 > 192.168.1.105.5672: Flags [P.], cksum 0x60c4 (correct), seq 1774776879:1774776912, ack 2398473446, win 1455, options [nop,nop,TS val 3735041620 ecr 607706177], length 33
16:47:29.781577 IP (tos 0x0, ttl 64, id 58859, offset 0, flags [DF], proto TCP (6), length 86)
    192.168.1.105.5672 > 192.168.1.148.34824: Flags [P.], cksum 0x8496 (incorrect -> 0x2ac9), seq 2398473446:2398473480, ack 1774776912, win 1463, options [nop,nop,TS val 607706181 ecr 3735041620], length 34
16:47:29.825527 IP (tos 0x0, ttl 64, id 55107, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.1.148.34824 > 192.168.1.105.5672: Flags [.], cksum 0x8101 (correct), seq 1774776912, ack 2398473480, win 1455, options [nop,nop,TS val 3735041624 ecr 607706181], length 0
16:47:59.791299 IP (tos 0x0, ttl 64, id 58860, offset 0, flags [DF], proto TCP (6), length 60)
    192.168.1.105.5672 > 192.168.1.148.34824: Flags [P.], cksum 0x847c (incorrect -> 0x02e1), seq 2398473480:2398473488, ack 1774776912, win 1463, options [nop,nop,TS val 607736191 ecr 3735041624], length 8
16:47:59.791717 IP (tos 0x0, ttl 64, id 55108, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.1.148.34824 > 192.168.1.105.5672: Flags [.], cksum 0x9685 (correct), seq 1774776912, ack 2398473488, win 1455, options [nop,nop,TS val 3735071633 ecr 607736191], length 0

[migration happens here...]

16:48:08.384507 IP (tos 0x0, ttl 64, id 11569, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.1.132.34824 > 192.168.1.105.5672: Flags [.], cksum 0xfcb8 (correct), seq 1774776911, ack 2398473488, win 1455, options [nop,nop,TS val 3735075623 ecr 0], length 0
16:48:08.384548 IP (tos 0x0, ttl 64, id 40732, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.1.105.5672 > 192.168.1.132.34824: Flags [.], cksum 0x8464 (incorrect -> 0x15bc), seq 2398473488, ack 1774776912, win 1463, options [nop,nop,TS val 607739011 ecr 0], length 0
16:48:08.392623 IP (tos 0x0, ttl 64, id 40733, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.1.105.5672 > 192.168.1.132.34824: Flags [.], cksum 0x8464 (incorrect -> 0x15b5), seq 2398473487, ack 1774776912, win 1463, options [nop,nop,TS val 607739019 ecr 0], length 0
16:48:08.393001 IP (tos 0x0, ttl 64, id 11570, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.1.132.34824 > 192.168.1.105.5672: Flags [.], cksum 0x7bf2 (correct), seq 1774776912, ack 2398473488, win 1455, options [nop,nop,TS val 3735075632 ecr 607739011], length 0

[communication continues correctly back on original host...]
```

**Comment by avagin** [comment]
> Shortly after the section I posted from the tcpdump, the applications send [P.] repeatedly back and forth to each other, then don't communicate with each other for 30 seconds, then send a single message, then don't do anything again until I migrate the client back to the original host it came from.

Have you tried to look what processes are doing during these 30 seconds? I think a tcp connection is fully functional, but processes don't send any data. You can run strace (strace -fp PID -s 256) for processes after migration.

**Comment by dav-ell** [comment]
> You can run strace (strace -fp PID -s 256) for processes after migration.

I did this, and what it looks like before migration is this:
```
...
[pid 18131] epoll_wait(3, [{EPOLLIN, {u32=10, u64=10}}], 1024, 999) = 1
[pid 18131] read(10, "\1\0\1\0\0\0\32\0002\0\v\rstory-channel\0\0\0\0\0\0\0\1\316", 65536) = 34
[pid 18131] epoll_wait(3, [], 1024, 998) = 0
[pid 18131] write(1, "Sent h\n", 7) 	= 7
[pid 18131] epoll_wait(3, [], 1024, 0)  = 0
[pid 18131] write(10, "\1\0\1\0\0\0\31\0002\0\n\0\0\rstory-channel\0\0\0\0\0\316", 33) = 33
[pid 18131] write(10, "\1\0\1\0\0\0\26\0<\0(\0\0\0\rstory-channel\0\316\2\0\1\0\0\0\22\0<\0\0\0\0\0\0\0\0\0\1 \0\0\0\0\0\316\3\0\1\0\0\0\1h\316", 65) = 65
[pid 18131] epoll_ctl(3, EPOLL_CTL_MOD, 10, {EPOLLIN, {u32=10, u64=10}}) = 0
[pid 18131] epoll_wait(3, [{EPOLLIN, {u32=10, u64=10}}], 1024, 999) = 1
[pid 18131] read(10, "\1\0\1\0\0\0\32\0002\0\v\rstory-channel\0\0\0\0\0\0\0\1\316", 65536) = 34
...
```

After migration it looks like this:
```
strace: Process 6545 attached with 10 threads
[pid  6658] futex(0x21afa44, FUTEX_WAIT_PRIVATE, 12, NULL <unfinished ...>
[pid  6655] futex(0x21afa44, FUTEX_WAIT_PRIVATE, 12, NULL <unfinished ...>
[pid  6657] futex(0x21afa44, FUTEX_WAIT_PRIVATE, 12, NULL <unfinished ...>
[pid  6656] futex(0x21afa44, FUTEX_WAIT_PRIVATE, 12, NULL <unfinished ...>
[pid  6654] futex(0x21af820, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  6653] futex(0x2426d14, FUTEX_WAIT_PRIVATE, 32, NULL <unfinished ...>
[pid  6652] futex(0x2426d14, FUTEX_WAIT_PRIVATE, 32, NULL <unfinished ...>
[pid  6651] futex(0x2426d14, FUTEX_WAIT_PRIVATE, 32, NULL <unfinished ...>
[pid  6650] futex(0x2426d14, FUTEX_WAIT_PRIVATE, 32, NULL <unfinished ...>
[pid  6545] epoll_wait(3, [{EPOLLIN, {u32=10, u64=10}}], 1024, 100146735) = 1
[pid  6545] brk(0x2a8a000)              = 0x2a8a000
[pid  6545] read(10, "\10\0\0\0\0\0\0\316", 65536) = 8
[pid  6545] epoll_wait(3, [{EPOLLIN, {u32=10, u64=10}}], 1024, 50048181) = 1
[pid  6545] read(10, "\10\0\0\0\0\0\0\316", 65536) = 8
[pid  6545] epoll_wait(3, [{EPOLLIN, {u32=10, u64=10}}], 1024, 49988207) = 1
[pid  6545] read(10, "", 65536)         = 0
[pid  6545] epoll_ctl(3, EPOLL_CTL_DEL, 10, 0x7fff67155d80) = 0
[pid  6545] close(10)                   = 0
[pid  6545] write(2, "events.js:112\n      throw er; // Unhandled 'error' event\n      ^\n\nError: Unexpected close\n    at succeed (/node_modules/amqplib/lib/connection.js:271:13)\n    at onOpenOk (/node_modules/amqplib/lib/connection.js:253:5)\n    at /node_modules/amqplib/lib/conne"..., 763) = 763
```
These lines were generated over the course of 2 minutes, with most of the time being in `epoll_wait`.

Is it possible that some of the upper-layer protocols may have been disrupted during the migration? We're using AMQP connections here. I had thought C/R for TCP would have been transparent to any protocols above, though.

I also considered that it could be the application itself (RabbitMQ). The only problem is that the migration works many times until suddenly this problem occurs, and after that migrating it again to that host will cause it to experience this problem.

> I need tcp image files to investigate this issue.

Here are the files.

[checkpoint.tar.txt](https://github.com/checkpoint-restore/criu/files/2263032/checkpoint.tar.txt)
[logs.tar.txt](https://github.com/checkpoint-restore/criu/files/2263033/logs.tar.txt)

**Comment by avagin** [comment]
> [pid  6545] read(10, "", 65536)         = 0
Here the file descriptor 10 is a tcp socket. You need to understand why it was closed after C/R. I think you can try to use tcpdump and try to strace a process which handles another side of this connection.
