### ISSUE TITLE
criu restore of zdtm/static/clone_fs hangs up

### ISSUE THREAD

**Issue by avagin** [checkpoint-restore/criu#531]
https://ci.openvz.org/job/CRIU/job/CRIU-x86_64-dedup/job/master/3730/console
```
[root@zdtm /]# ps axf
  PID TTY      STAT   TIME COMMAND
   38 ?        S      0:00 -bash
   65 ?        R+     0:00  \_ ps axf
    1 ?        S      0:00 python zdtm.py
    3 ?        S      0:00 python zdtm.py
   41 ?        S      0:00  \_ ../criu/criu restore -o restore.log -D dump/zdtm/static/clone_fs/36/3 -v4 --pidfile /mnt/test/zdtm/static/clone_fs.pid --restore-detached
   36 ?        Ssl    0:00      \_ ./clone_fs --pidfile=clone_fs.pid --outfile=clone_fs.out
```
```
(gdb) 
#0  0x00007f9ba089fa39 in syscall () from target:/lib64/libc.so.6
#1  0x000000000043c1ed in sys_futex (addr2=0x0, val3=0, timeout=0x7fff47946630, val1=<optimized out>, op=0, addr1=0x7f9ba1c0f00c) at include/common/lock.h:25
#2  __restore_wait_inprogress_tasks (participants=participants@entry=0) at criu/cr-restore.c:180
#3  0x000000000043cd34 in restore_wait_inprogress_tasks () at criu/cr-restore.c:224
#4  restore_switch_stage (next_stage=4) at criu/cr-restore.c:224
#5  restore_root_task (init=0x7f9ba1c18050) at criu/cr-restore.c:2181
#6  0x000000000043de5a in cr_restore_tasks () at criu/cr-restore.c:2391
#7  0x0000000000421d1d in main (argc=<optimized out>, argv=0x7fff479468c8, envp=<optimized out>) at criu/crtools.c:765
(gdb) bt
#0  0x00007f9ba089fa39 in syscall () from /lib64/libc.so.6
#1  0x000000000043c1ed in sys_futex (addr2=0x0, val3=0, timeout=0x7fff47946630, val1=<optimized out>, op=0, addr1=0x7f9ba1c0f00c) at include/common/lock.h:25
#2  __restore_wait_inprogress_tasks (participants=participants@entry=0) at criu/cr-restore.c:180
#3  0x000000000043cd34 in restore_wait_inprogress_tasks () at criu/cr-restore.c:224
#4  restore_switch_stage (next_stage=4) at criu/cr-restore.c:224
#5  restore_root_task (init=0x7f9ba1c18050) at criu/cr-restore.c:2181
#6  0x000000000043de5a in cr_restore_tasks () at criu/cr-restore.c:2391
#7  0x0000000000421d1d in main (argc=<optimized out>, argv=0x7fff479468c8, envp=<optimized out>) at criu/crtools.c:765
(gdb) frame 3
#3  0x000000000043cd34 in restore_wait_inprogress_tasks () at criu/cr-restore.c:224
224		return restore_wait_inprogress_tasks();
(gdb) frame 2
#2  __restore_wait_inprogress_tasks (participants=participants@entry=0) at criu/cr-restore.c:180
180		futex_wait_while_gt(np, participants);
(gdb) p np
np            nptl_freeres  nptl_version  
(gdb) p np
$1 = (futex_t *) 0x7f9ba1c0f00c
(gdb) p *np
$2 = {raw = {counter = 1}}
(gdb) p participants
$3 = 0
(gdb)
```

**Comment by avagin** [comment]
```
(00.022070) pie: 36: vdso: DT_STRSZ: 0x5e
(00.022072) pie: 36: vdso: DT_SYMENT: 0x18
(00.022073) pie: 36: vdso: nbucket 0x3 nchain 0xa bucket 0x7ffdd01ec128 chain 0x7ffdd01ec134
(00.022076) pie: 36: vdso: image [vdso] 0x7ffdd01ec000-0x7ffdd01ee000 [vvar] 0x7ffdd01e9000-0x7ffdd01ec000
(00.022078) pie: 36: vdso: Runtime vdso/vvar matches dumpee, remap inplace
(00.022084) pie: 36: vdso: Remap rt-vdso 0x33000 -> 0x7ffdd01ec000
(00.022091) pie: 36: vdso: Remap rt-vvar 0x30000 -> 0x7ffdd01e9000
(00.022129) pie: 36: Restoring scheduler params 0.0.0
(00.022180) pie: 36: 36: Restored
(00.022181) pie: 37: Restoring scheduler params 0.0.0
(00.022191) pie: 37: 37: Restored
```

**Comment by avagin** [comment]
It is reproduced again:
```
[root@zdtm mnt]# ps axf
  PID TTY      STAT   TIME COMMAND
  160 ?        S      0:00 -bash
  709 ?        R+     0:00  \_ ps axf
    1 ?        S      0:00 python zdtm.py
    3 ?        S      0:00 python zdtm.py
  143 ?        S      0:00  \_ ../criu/criu restore -o restore.log -D dump/zdtm/static/sse00/77/4 -v4 --pidfile /mnt/test/zdtm/static/sse00.pid --root /tmp/criu-root-O4oxbF --restore-detache
  144 ?        Ss     0:00      \_ ./sse00 --pidfile=sse00.pid --outfile=sse00.out
  159 ?        Ss     0:00          \_ ./sse00 --pidfile=sse00.pid --outfile=sse00.out

[root@zdtm mnt]# gdb -p 143
(gdb) bt
#0  0x00007f4fbf8f0ae9 in syscall () from /lib64/libc.so.6
#1  0x000000000043c1ed in sys_futex (addr2=0x0, val3=0, timeout=0x7ffc11c4b860, val1=<optimized out>, op=0, addr1=0x7f4fc0c6000c) at include/common/lock.h:25
#2  __restore_wait_inprogress_tasks (participants=participants@entry=0) at criu/cr-restore.c:180
#3  0x000000000043cd34 in restore_wait_inprogress_tasks () at criu/cr-restore.c:224
#4  restore_switch_stage (next_stage=4) at criu/cr-restore.c:224
#5  restore_root_task (init=0x7f4fc0c69050) at criu/cr-restore.c:2181
#6  0x000000000043de5a in cr_restore_tasks () at criu/cr-restore.c:2391
#7  0x0000000000421d1d in main (argc=<optimized out>, argv=0x7ffc11c4baf8, envp=<optimized out>) at criu/crtools.c:765
(gdb) p *task_entries
$2 = {nr_threads = 2, nr_tasks = 2, nr_helpers = 0, nr_in_progress = {raw = {counter = 1}}, start = {raw = {counter = 4}}, cr_err = {counter = 0}, userns_sync_lock = {raw = {counter = 0}}}
(gdb) 
[root@zdtm mnt]# strace -fp 159
strace: Process 159 attached
futex(0x25010, FUTEX_WAIT, 4, NULL^Cstrace: Process 159 detached
 <detached ...>
[root@zdtm mnt]# strace -fp 144
strace: Process 144 attached
futex(0x25010, FUTEX_WAIT, 4, NULL^Cstrace: Process 144 detached
 <detached ...>

[root@zdtm mnt]# uname -a
Linux zdtm.openvz.org 4.17.19-200.fc28.x86_64 #1 SMP Fri Aug 24 15:47:41 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by geminijun** [comment]
Are there any updates on this issue? I believe I'm hitting this one when tried to restore KDB, it happens occasionally, I still don't know in which condition it will happen, will update it later.

**Comment by avagin** [comment]
What is KDB?

**Comment by avagin** [comment]
I am not sure that this is the same issue. I think you need to create a new issue and describe in detail what is going on there.
