### ISSUE TITLE
zdtm/static/pty02 hangs up

### ISSUE THREAD

**Issue by avagin** [checkpoint-restore/criu#647]
```
 1449 ?        Ss     0:01 /usr/sbin/sshd -D
 2178 ?        Ss     0:36  \_ sshd: root@notty
 2315 ?        Ssl   25:03  |   \_ java -jar remoting.jar -workDir /var/lib/jenkins
19473 ?        S      0:00  |       \_ /bin/sh -xe /tmp/jenkins4065330272773810023.sh
19476 ?        S      0:00  |           \_ /bin/sh ./test/jenkins/run_ct sh -c mount --make-rprivate / && mount --rbind . /mnt && cd /mnt &&  ./test/jenkins/criu-sibling.sh
19480 ?        S      0:00  |               \_ unshare --mount --pid --fork -- /var/lib/jenkins/workspace/IU-restore-sibling_criu-dev-VLVF62J7352BK6F3A6XZQPCEF6Y4QGZPRDPZ7KDBAFOSNOSNCYHQ/tes
19481 ?        S      0:00  |                   \_ sh -c mount --make-rprivate / && mount --rbind . /mnt && cd /mnt &&  ./test/jenkins/criu-sibling.sh
29517 ?        S      0:02  |                       \_ python ./test/zdtm.py run --all --keep-going --report report --sibling --parallel 4 -x maps04
21330 ?        S      0:00  |                           \_ ./zdtm_ct zdtm.py
21376 ?        S      0:00  |                               \_ python zdtm.py
21398 ?        S      0:00  |                                   \_ python zdtm.py
22173 ?        Ss     0:00  |                                       \_ ./pty02 --pidfile=pty02.pid --outfile=pty02.out
22188 pts/0    Ss+    0:00  |                                           \_ ./pty02 --pidfile=pty02.pid --outfile=pty02.out
22189 ?        S      0:00  |                                               \_ ./pty02 --pidfile=pty02.pid --outfile=pty02.out
```

```
(gdb) bt
root@criu-test:~# gdb -p 22189
#0  0x00007f79fcda9f31 in __GI___libc_read (fd=6, buf=buf@entry=0x7fffdc705e1c, nbytes=nbytes@entry=4) at ../sysdeps/unix/sysv/linux/read.c:26
#1  0x0000563eb35ddca9 in task_waiter_wait4 (t=0x7fffdc705e80, lockid=1) at lock.c:42
#2  0x0000563eb35dc6d7 in main (argc=<optimized out>, argv=<optimized out>) at pty02.c:69

root@criu-test:~# gdb -p 22188
(gdb) bt
#0  0x00007f79fcda9f31 in __GI___libc_read (fd=5, buf=0x7fffdc705e92, nbytes=5) at ../sysdeps/unix/sysv/linux/read.c:26
#1  0x0000563eb35dc640 in main (argc=<optimized out>, argv=<optimized out>) at pty02.c:86

root@criu-test:~# gdb -p 22173
(gdb) bt
#0  0x00007f79fcd7e3b7 in __GI___waitpid (pid=pid@entry=-1, stat_loc=stat_loc@entry=0x7fffdc6c5c28, options=options@entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
#1  0x0000563eb35de770 in ns_init (argc=argc@entry=3, argv=argv@entry=0x7fffdc705fa8) at ns.c:345
#2  0x0000563eb35dd5bc in test_init (argc=3, argv=0x7fffdc705fa8) at test.c:234
#3  0x0000563eb35dc58f in main (argc=<optimized out>, argv=<optimized out>) at pty02.c:31

root@criu-test:~# cat /proc/22173/cwd/pty02.out.inprogress 
root@criu-test:~# cat /proc/22173/cwd/pty02.outns 
Time to stop and check
kill(4, SIGTERM)

```
https://ci.openvz.org/job/CRIU/job/CRIU-restore-sibling/job/criu-dev/

**Comment by avagin** [comment]
```
root@criu-test:~# ( set -x; for i in `ps -C pty02 -o pid h`; do ls -l /proc/$i/fd;  done )
++ ps -C pty02 -o pid h
+ for i in `ps -C pty02 -o pid h`
+ ls --color=auto -l /proc/22173/fd
total 0
lrwx------ 1 20000 400000 64 Mar 10 20:27 0 -> /dev/null
l-wx------ 1 20000 400000 64 Mar 10 20:30 1 -> /zdtm/static/pty02.outns
l-wx------ 1 20000 400000 64 Mar 10 20:30 2 -> /zdtm/static/pty02.outns
lr-x------ 1 20000 400000 64 Mar 10 20:30 3 -> /zdtm/static/pty02.pidns
+ for i in `ps -C pty02 -o pid h`
+ ls --color=auto -l /proc/22188/fd
total 0
lrwx------ 1 38943 508467 64 Mar 10 20:27 0 -> /dev/null
l-wx------ 1 38943 508467 64 Mar 10 20:30 1 -> /zdtm/static/pty02.out.inprogress
l-wx------ 1 38943 508467 64 Mar 10 20:30 2 -> /zdtm/static/pty02.out.inprogress
lr-x------ 1 38943 508467 64 Mar 10 20:30 3 -> /zdtm/static
lrwx------ 1 38943 508467 64 Mar 10 20:30 5 -> /dev/pts/0
lr-x------ 1 38943 508467 64 Mar 10 20:30 6 -> 'pipe:[39128683]'
l-wx------ 1 38943 508467 64 Mar 10 20:30 7 -> 'pipe:[39128683]'
+ for i in `ps -C pty02 -o pid h`
+ ls --color=auto -l /proc/22189/fd
total 0
lrwx------ 1 38943 508467 64 Mar 10 20:25 0 -> /dev/null
l-wx------ 1 38943 508467 64 Mar 10 20:30 1 -> /zdtm/static/pty02.out.inprogress
l-wx------ 1 38943 508467 64 Mar 10 20:30 2 -> /zdtm/static/pty02.out.inprogress
lr-x------ 1 38943 508467 64 Mar 10 20:30 3 -> /zdtm/static
lrwx------ 1 38943 508467 64 Mar 10 20:30 4 -> /dev/pts/ptmx
lrwx------ 1 38943 508467 64 Mar 10 20:30 5 -> /dev/pts/0
lr-x------ 1 38943 508467 64 Mar 10 20:30 6 -> 'pipe:[39128683]'
l-wx------ 1 38943 508467 64 Mar 10 20:30 7 -> 'pipe:[39128683]'
lrwx------ 1 38943 508467 64 Mar 10 20:30 8 -> /dev/pts/ptmx

```

**Comment by avagin** [comment]
```
root@criu-test:~# /proc/19480/cwd/crit/crit show /proc/21398/cwd/dump/zdtm/static/pty02/168/1/tty-data.img
{
    "magic": "TTY_DATA", 
    "entries": [
        {
            "tty_id": 0, 
            "data": "cGluZwo=\n"
        }, 
        {
            "tty_id": 1, 
            "data": "cGluZw0K\n"
        }
    ]
}

```

**Comment by avagin** [comment]
```
root@criu-test:~# /proc/19480/cwd/crit/crit show /proc/21398/cwd/dump/zdtm/static/pty02/168/1/tty-info.img 
{
    "magic": "TTY_INFO", 
    "entries": [
        {
            "id": 0, 
            "type": "PTY", 
            "locked": false, 
            "exclusive": false, 
            "packet_mode": false, 
            "sid": 4, 
            "pgrp": 4, 
            "rdev": 34816, 
            "termios": {
                "c_iflag": 1280, 
                "c_oflag": 5, 
                "c_cflag": 191, 
                "c_lflag": 35387, 
                "c_line": 0, 
                "c_ispeed": 0, 
                "c_ospeed": 0, 
                "c_cc": [
                    360651779, 
                    65540, 
                    1708817, 
                    370609938, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0
                ]
            }, 
            "termios_locked": {
                "c_iflag": 0, 
                "c_oflag": 0, 
                "c_cflag": 0, 
                "c_lflag": 0, 
                "c_line": 0, 
                "c_ispeed": 0, 
                "c_ospeed": 0, 
                "c_cc": [
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0
                ]
            }, 
            "winsize": {
                "ws_row": 0, 
                "ws_col": 0, 
                "ws_xpixel": 0, 
                "ws_ypixel": 0
            }, 
            "pty": {
                "index": 0
            }, 
            "dev": 50, 
            "uid": 18943, 
            "gid": 58467
        }, 
        {
            "id": 1, 
            "type": "PTY", 
            "locked": false, 
            "exclusive": false, 
            "packet_mode": false, 
            "sid": 4, 
            "pgrp": 4, 
            "rdev": 1282, 
            "termios": {
                "c_iflag": 1280, 
                "c_oflag": 5, 
                "c_cflag": 191, 
                "c_lflag": 35387, 
                "c_line": 0, 
                "c_ispeed": 0, 
                "c_ospeed": 0, 
                "c_cc": [
                    360651779, 
                    65540, 
                    1708817, 
                    370609938, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0
                ]
            }, 
            "termios_locked": {
                "c_iflag": 0, 
                "c_oflag": 0, 
                "c_cflag": 0, 
                "c_lflag": 0, 
                "c_line": 0, 
                "c_ispeed": 0, 
                "c_ospeed": 0, 
                "c_cc": [
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0
                ]
            }, 
            "winsize": {
                "ws_row": 0, 
                "ws_col": 0, 
                "ws_xpixel": 0, 
                "ws_ypixel": 0
            }, 
            "pty": {
                "index": 0
            }, 
            "dev": 50, 
            "uid": 0, 
            "gid": 0
        }
    ]
}
```

**Comment by cyrillos** [comment]
What kernel is it?

**Comment by cyrillos** [comment]
Will try to take a precise look tomorrow. Thanks!
