### ISSUE TITLE
dump error

### ISSUE THREAD

**Issue by weiwang999** [checkpoint-restore/criu#689]
dump error and No such process. It's really weird and actually it is shown that the process is running by the command ps -C popcorn-game-server
   PID TTY          TIME CMD
 75195 pts/13   00:00:00 popcorn-game-se
pid: 75195,  status: 0 
Error (criu/cr-dump.c:1447): Timeout reached. Try to interrupt: 0
ret -1
error waitpid
: Interrupted system call
Error (compel/src/lib/infect.c:363): Unable to detach from 75195: No such process
Error (criu/cr-dump.c:1732): Dumping FAILED.
Traceback (most recent call last):
  File "/usr/local/bin/crit", line 6, in <module>
    cli.main()
  File "/usr/local/lib/python2.7/dist-packages/pycriu/cli.py", line 369, in main
    opts["func"](opts)
  File "/usr/local/lib/python2.7/dist-packages/pycriu/cli.py", line 58, in recode
    converter.recode(arch, directory, outdir, path_append)
  File "/usr/local/lib/python2.7/dist-packages/pycriu/het.py", line 449, in recode
    self.__recode_pid(_pid, arch, directory, outdir, onlyfiles, path_append)
  File "/usr/local/lib/python2.7/dist-packages/pycriu/het.py", line 406, in __recode_pid
    dest_files=self.get_target_files(files_file, mm_file, path_append) #must be after get_target_core
  File "/usr/local/lib/python2.7/dist-packages/pycriu/het.py", line 1104, in get_target_files
    copyfile(path_aarch64, path)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 26] Text file busy: '/popcorn/game-server/popcorn-game-server'
helios@helios-PowerEdge-R7425:/popcorn/game-server$ ps -C popcorn-game-server
   PID TTY          TIME CMD
 75195 pts/13   00:00:00 popcorn-game-se

**Comment by avagin** [comment]
I don't understand what you wrote here. Pls, describe a problem, give steps to reproduce and attach full criu logs.
