### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '::'

### ISSUE THREAD

**Issue by avagin** [checkpoint-restore/criu#708]
https://ci.openvz.org/job/CRIU/job/CRIU-crit/job/criu-dev/5144/console

```
Traceback (most recent call last):
  File "./test/crit-recode.py", line 66, in <module>
    if not recode_and_check(imgf, o_img, True):
  File "./test/crit-recode.py", line 27, in recode_and_check
    r_img = pycriu.images.dumps(pb)
  File "/var/lib/jenkins/workspace/CRIU_CRIU-crit_criu-dev-DBNKUFN2EIV77FCLF3JCP2VBDOBGR7GVBO3FUACODQLMNTD7X6AQ/test/pycriu/images/images.py", line 595, in dumps
    dump(img, f)
  File "/var/lib/jenkins/workspace/CRIU_CRIU-crit_criu-dev-DBNKUFN2EIV77FCLF3JCP2VBDOBGR7GVBO3FUACODQLMNTD7X6AQ/test/pycriu/images/images.py", line 587, in dump
    handler.dump(img['entries'], f)
  File "/var/lib/jenkins/workspace/CRIU_CRIU-crit_criu-dev-DBNKUFN2EIV77FCLF3JCP2VBDOBGR7GVBO3FUACODQLMNTD7X6AQ/test/pycriu/images/images.py", line 142, in dump
    pb2dict.dict2pb(entry, pbuff)
  File "/var/lib/jenkins/workspace/CRIU_CRIU-crit_criu-dev-DBNKUFN2EIV77FCLF3JCP2VBDOBGR7GVBO3FUACODQLMNTD7X6AQ/test/pycriu/images/pb2dict.py", line 367, in dict2pb
    dict2pb(value, getattr(pb, field.name, None))
  File "/var/lib/jenkins/workspace/CRIU_CRIU-crit_criu-dev-DBNKUFN2EIV77FCLF3JCP2VBDOBGR7GVBO3FUACODQLMNTD7X6AQ/test/pycriu/images/pb2dict.py", line 359, in dict2pb
    pb_val.append(_dict2pb_cast(field, v))
  File "/var/lib/jenkins/workspace/CRIU_CRIU-crit_criu-dev-DBNKUFN2EIV77FCLF3JCP2VBDOBGR7GVBO3FUACODQLMNTD7X6AQ/test/pycriu/images/pb2dict.py", line 326, in _dict2pb_cast
    return cast(value)
ValueError: invalid literal for int() with base 10: '::'

```

**Comment by avagin** [comment]
This was broken by 22c23bb63351c3914f2a9c55cf7fb3cb09a4f3a8

**Comment by avagin** [comment]
we need something like this:
```
diff --git a/lib/py/images/pb2dict.py b/lib/py/images/pb2dict.py
index 4e2c171d5..b6212e99f 100644
--- a/lib/py/images/pb2dict.py
+++ b/lib/py/images/pb2dict.py
@@ -219,7 +219,7 @@ def is_string(value):
        # Python 3 compatibility
        if not hasattr(__builtins__, "basestring"):
                basestring = (str, bytes)
-       return isinstance(value, basestring)
+       return isinstance(value, basestring) or isinstance(value, unicode)
 
 def _pb2dict_cast(field, value, pretty = False, is_hex = False):
        if not is_hex:
```

**Comment by rst0git** [comment]
The error here was because for some reason `hasattr(__builtins__, "basestring")` here returns `False` in Python 2. Using `sys.version_info` instead seems to work.

Also, testing the `is_string()` function in Python 2 failed as follows:
```
>>> def is_string(value):
...     if not hasattr(__builtins__, "basestring"):
...             basestring = (str, bytes)
...     return isinstance(value, basestring)
... 
>>> is_string("test")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 4, in is_string
UnboundLocalError: local variable 'basestring' referenced before assignment
```
These and a few other issues are fixed in https://github.com/checkpoint-restore/criu/pull/709.
