### ISSUE TITLE
zdtm: seccomp_filter_threads and seccomp_filter_tsync fail with Alpine 3.10

### ISSUE THREAD

**Issue by rst0git** [checkpoint-restore/criu#725]
The following two tests fail with [Alpine 3.10](https://api.travis-ci.org/v3/job/549062657/log.txt) (and edge) but the pass with [3.9 and earlier versions](https://api.travis-ci.org/v3/job/549183514/log.txt)

* zdtm/static/seccomp_filter_threads(h)
* zdtm/static/seccomp_filter_tsync(h)

The issue can be reproduced by running the above two test cases in a docker container:
```sh
docker run -it --privileged alpine:3.9 sh # or alpine:3.10
apk add gcc bash build-base ccache coreutils git gnutls-dev libaio-dev libcap-dev libnet-dev libnl3-dev pkgconfig protobuf-c-dev protobuf-dev python sudo py-yaml py-pip py2-future ip6tables iptables iproute2 tar go e2fsprogs asciidoctor
pip install protobuf ipaddress junit_xml
git clone https://github.com/checkpoint-restore/criu/
cd criu && make
cd test && ./zdtm.py run -t zdtm/static/seccomp_filter_threads
```

**Comment by avagin** [comment]
pthread_join() doesn't work properly. I think the problem is in musl. @rst0git, could you report this problem into the musl mailing list.

```
(gdb) bt
#0  __cp_end () at src/thread/x86_64/syscall_cp.s:29
#1  0x00007fbe40a1e4b6 in __syscall_cp_c (nr=202, u=<optimized out>, v=<optimized out>, w=<optimized out>, x=<optimized out>, y=<optimized out>, z=0) at src/thread/pthread_cancel.c:33
#2  0x00007fbe40a1dacf in __timedwait_cp (addr=addr@entry=0x7fbe409cab60, val=1, clk=clk@entry=0, at=at@entry=0x0, priv=<optimized out>, priv@entry=1) at src/thread/__timedwait.c:31
#3  0x00007fbe40a1f666 in __pthread_timedjoin_np (t=0x7fbe409cab20, res=0x7fff58199bb8, at=0x0) at src/thread/pthread_join.c:17
#4  0x0000562ffec566a9 in main (argc=<optimized out>, argv=<optimized out>) at seccomp_filter_threads.c:183

```

```
bash-5.0# ls -l /proc/11857/task/
total 0
dr-xr-xr-x 7 root root 0 Jun 24 17:59 11857
```

Steps to run this test manually without C/R:
```
cd test/zdtm/static
make seccomp_filter_threads.cleanout
strace -fo strace.log -s 256 make seccomp_filter_threads.out
```

**Comment by rst0git** [comment]
yes, the problem is in musl. It occurs since [this commit](https://git.musl-libc.org/cgit/musl/commit/?id=8f11e6127fe93093f81a52b15bb1537edc3fc8af).

**Comment by rst0git** [comment]
https://www.openwall.com/lists/musl/2019/06/25/4
