### ISSUE TITLE
TypeError: Conflict register for file "sk-opts.proto": READ is already defined in file "rpc.proto". 

### ISSUE THREAD

**Issue by avagin** [checkpoint-restore/criu#815]
```
+ ./test/zdtm.py run -a -p 2 --keep-going -x zdtm/static/binfmt_misc -x zdtm/static/sched_policy00
Traceback (most recent call last):
  File "./test/zdtm.py", line 27, in <module>
    import pycriu as crpc
  File "/criu/test/pycriu/__init__.py", line 2, in <module>
    from . import images
  File "/criu/test/pycriu/images/__init__.py", line 4, in <module>
    from .images import *
  File "/criu/test/pycriu/images/images.py", line 47, in <module>
    from . import pb
  File "/criu/test/pycriu/images/pb.py", line 16, in <module>
    from .fdinfo_pb2 import *
  File "/criu/test/pycriu/images/fdinfo_pb2.py", line 17, in <module>
    import sk_inet_pb2 as sk__inet__pb2
  File "/criu/test/pycriu/images/sk_inet_pb2.py", line 17, in <module>
    import sk_opts_pb2 as sk__opts__pb2
  File "/criu/test/pycriu/images/sk_opts_pb2.py", line 54, in <module>
    _sym_db.RegisterEnumDescriptor(_SK_SHUTDOWN)
  File "/usr/lib/python2.7/site-packages/google/protobuf/symbol_database.py", line 107, in RegisterEnumDescriptor
    self.pool._AddEnumDescriptor(enum_descriptor)
  File "/usr/lib/python2.7/site-packages/google/protobuf/descriptor_pool.py", line 280, in _AddEnumDescriptor
    self._CheckConflictRegister(enum_value, full_name, file_name)
  File "/usr/lib/python2.7/site-packages/google/protobuf/descriptor_pool.py", line 191, in _CheckConflictRegister
    raise TypeError(error_msg)
TypeError: Conflict register for file "sk-opts.proto": READ is already defined in file "rpc.proto". Please fix the conflict by adding package name on the proto file, or use different name for the duplication.
Note: enum values appear as siblings of the enum type instead of children of it.
Makefile:27: recipe for target 'alpine' failed
```

**Comment by avagin** [comment]
https://travis-ci.org/checkpoint-restore/criu/jobs/594019238

**Comment by avagin** [comment]
Cc: @dubeyabhishek
